### ISSUE TITLE
Vulnerabilities are not showing in issues list

### ISSUE THREAD

**Issue by eonicle** [dependency-check/dependency-check-sonar-plugin#167]
**Describe the bug**
After scanning, projects failing quality gate show "Critical severity vulnerabilities" on dashboard. When clicking on it, I get redirected to "Measures" page instead of "Issues". Trying to lower all issues  severity does not help.

**To Reproduce**
1. Set quality gate to "Critical Severity Vulnerabilities | is greater than | 0"
2. Run dependency scan on project and send report with sonar scanner.
3. Click on quality gate popup "Critical severity vulnerabilities"

**Expected behavior**
When clicking in popup, I should get redirected to "Issues" list, or at least this issues should be visible.

**Screenshots**
I am clicking on first box
![Screen Shot 2019-09-03 at 6 08 13 PM](https://user-images.githubusercontent.com/26312750/64188099-6ce83500-ce7a-11e9-9639-b93aaa08bfdd.png)

This is where I get redirected
![Screen Shot 2019-09-03 at 6 08 20 PM](https://user-images.githubusercontent.com/26312750/64188167-8d17f400-ce7a-11e9-853e-340004a06db2.png)

**Versions (please complete the following information):**
 - dependency-check - 5.2.1
 - sonarqube - 7.9.1.27448
 - dependency-check-sonar-plugin - 1.2.5

**Additional context**
The biggest problem is that we can't see this issues, so we have to remove rules from quality gate.

**Comment by Reamer** [comment]
Hi @eonicle,
I can reproduce redirect behaviour. The link for the quality gate is generated by sonarqube and not by this plugin. In my opinion this redirect is good.
After redirect you'll see files, which contains `Critical Severity Vulnerabilities`. At the moment we support maven (pom.xml) and gradle (build.gradle). Next step is to support nodejs with package.json.

What project language do you have?

**Comment by eonicle** [comment]
Hi @Reamer,
Thanks for response. Indeed, most of our projects are either NodeJS or Typescript, a few Django-based Python as well.
The problem with current behaviour is that some of the issues in dependencies we can't fix right now. So we want to lower their priority to allow Quality Gate to pass and return to then later. Right now, as we can't access this issues as SonarQube issues, we have to change Quality Gate to more restrictive, thus allowing another issues to pass.
Is there any workaround for this? And what's the timeline for NodeJS support?

**Comment by Reamer** [comment]
Hi @eonicle,
You can access the issues via `issues` tab. Then you should filter by language `neutral`.
You can configure the score <-> issue severity mapping. Checkout the plugin configuration. sonar.dependencyCheck.severity.minor/major/critical/blocker should help you.

**Comment by Reamer** [comment]
@eonicle 
In last days, i rewrote the whole XML parsing parts from this plugin, now it's based on [Jackson](https://github.com/FasterXML/jackson). A JSON-Reportparser is now also implemented. A JSON parser is needed for `package.json`. Maybe I find some time in next days to implement the parts for `package.json`.

**Comment by Vampire** [comment]
I'm having a similar issue here.
We are still on SonarQube 7.5, so I'm using plugin version 1.1.6.
(Btw. v2 is missing from the compatibility matrix in the readme)
The report is parsed properly it seems.
If I open the project in SQ and go to `Measures` tab I see various numbers in the left tree for OWASP findings.
But the issues list shows no results, no matter what I select in the tree:
![grafik](https://user-images.githubusercontent.com/325196/72535747-57980400-3879-11ea-8ad9-2f44efd57897.png)

**Comment by Reamer** [comment]
@eonicle Checkout [plugin version 2.0.1 ](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/tag/2.0.1). I have implemented the nodejs support. Feedback is welcome.
Please open an new issue for python.

@Vampire Sonarqube 7.5 isn't supported anymore. Please update to latest [sonarqube LTS](https://www.sonarqube.org/sonarqube-7-9-lts/) or at least to SonarQube 7.6.

**Comment by Vampire** [comment]
Well, neither updating SonarQube, nor updating your plugin would have helped the least due to #207 and #208. ;-)
