### ISSUE TITLE
Issues not showing in C# solution

### ISSUE THREAD

**Issue by jimmycav** [dependency-check/dependency-check-sonar-plugin#168]
We have a C# solution with many projects. We generate the dependency check file once for the whole directory, then build and analyse it (similar to the node example on github). The report has some vulnerabilities, so we expect to see them in Sonar.

But after we run sonar scanner, there are no issues. The only things we can see are:

- Total number of dependencies in the measures screen - see below
- The HTML report when we click on OWASP dependencies tab

![image](https://user-images.githubusercontent.com/5732711/64305718-5e1d9180-cfe4-11e9-8431-564e52c4285d.png)

There are some warnings in the logs, such as:

WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'high_severity_vulns' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'medium_severity_vulns' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'low_severity_vulns' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'total_dependencies' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'vulnerable_dependencies' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'total_vulnerabilities' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'inherited_risk_score' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'vulnerable_component_ratio' is ignored.
WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'report' is ignored.

**Comment by Reamer** [comment]
Hi @jimmycav,
you get this warning, because this plugin and me doesn't know, to which file the issues should be linked. Has C# an equivalent file as Maven (`pom.xml`).
Maybe you can assist this project and add really small "Hello-World" example with some vulnerable dependencies to our example folder.

**Comment by jimmycav** [comment]
I've created a pull request with an example project, the readme contains instruction to build and analyse it.

The equivalent to a pom.xml file would be the csproj files

**Comment by jimmycav** [comment]
Having left this for a while, I have recently tested this with Sonar  8.4.2 and Dependency-Check 2.0.6 and it is all working nicely.
