### ISSUE TITLE
Organisation change

### ISSUE THREAD

**Issue by Reamer** [dependency-check/dependency-check-sonar-plugin#170]
Hi @bradflood and @pethers,
I had a small email conversation with Nicolas Bontoux from Sonarsource about violations of our current organization name ("SonarSecurityCommunity") and organization picture. Therefore I changed the picture of the organization. I'll also try to move this project to [SonarQubeCommunity](https://github.com/SonarQubeCommunity). I hope, this is also in your intention. Let me know, if it isn't.
Best Regards
Reamer

**Comment by Reamer** [comment]
Issue in Sonarsource Community Forum: https://community.sonarsource.com/t/move-dependency-check-sonar-plugin-to-sonarqubecommunity-organisation/14016

**Comment by pethers** [comment]
Sounds good-

**Comment by Reamer** [comment]
SonarQubeCommunity as an organisation is not possible. See https://community.sonarsource.com/t/move-dependency-check-sonar-plugin-to-sonarqubecommunity-organisation/14016/4

Any suggestions for a new organization name?

**Comment by bradflood** [comment]
@Reamer @pethers  I wonder if we should consider moving to the OWASP organization.   @jeremylong @vinodanandan do you have any thoughts? We took over the dependency-check-sonar-plugin from Steve Springett, but the organization name conflicts with some policy from SonarSource.  Is it worth investigating whether to move the project into the OWASP Github repo?

**Comment by jeremylong** [comment]
I have plans to move a lot of the ODC code to a new organization: https://github.com/dependency-check

Either the OWASP repo or the above dependency-check repo would likely work.

**Comment by Reamer** [comment]
@ejohn20 Can you provide a way to move projects to [dependency-check](https://github.com/dependency-check) organization?

**Comment by ejohn20** [comment]
@jeremylong owns the dependency-check organization. He created the azure-devops repo for me. He should be able to help you get the repo moved into the new org.

**Comment by Reamer** [comment]
Thanks @ejohn20 for your explanation.
If I could choose an organization , I would prefer [dependency-check](https://github.com/dependency-check), because I'm no OWASP member at the moment.

**Comment by jeremylong** [comment]
I just created a team in the new repo and invited @Reamer and @bradflood.  Once you accept the invite you should be able to transfer the repo to the new org.

**Comment by Reamer** [comment]
@pethers & @bradflood Is is okay to change to the [dependency-check](https://github.com/dependency-check) organization?
@jeremylong Thanks for fast invitation.

**Comment by Reamer** [comment]
Hi @jeremylong,
I transferred this project to your organization. Thanks for setup.
I tried to apply travis-ci in first step, but I can not activate the Integration. I hope you can help.

**Comment by jeremylong** [comment]
Just approved the CI.  I'll try to be on top of any other requests that come in.

**Comment by bradflood** [comment]
Hi @Reamer,  thanks for your leadership in managing the evolution of the dependency-check-sonar project.  The new org that @jeremylong created seems like a perfect place for this project.

**Comment by Reamer** [comment]
Hi @jeremylong 
Travis-CI is working now. Thanks for approval. I requested an other application access for Codacy, to check your code quality.
Nicolas Bontoux from SonarSource wrote me, that he has closed the thread about violations of trademarks. Many thanks to all those who made it possible to move to this organization at incredible speed.

**Comment by jeremylong** [comment]
done - codacy has been approved.

**Comment by Reamer** [comment]
It's working. Thanks
