### ISSUE TITLE
I cannot find dependency-check badge in dashboard

### ISSUE THREAD

**Issue by leizhen** [dependency-check/dependency-check-sonar-plugin#174]
**Describe the bug**
After building from jenkins, I visit sonarqube and cannot find dependency-check badge

**To Reproduce**
1. config jenkins to do dependency-check;
2. set up sonar scanner and add following parameters:
sonar.dependencyCheck.reportPath=${WORKSPACE}/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=${WORKSPACE}/dependency-check-report.html
sonar.dependencyCheck.summarize=true
3. publish dependency-check report after build;
4. go to sonarqube to see the result.

**Current behavior**
Cannot find dependency-check badge

**Expected behavior**
can find dependency-check badge

**Screenshots**

**Versions (please complete the following information):**
 - dependency-check
 - sonarqube
 - dependency-check-sonar-plugin

**Additional context**
sonarqube 7.9.1 with docker

![image](https://user-images.githubusercontent.com/4723765/65303455-acb85780-dbb0-11e9-8de4-86a21f3ef8a2.png)

![image](https://user-images.githubusercontent.com/4723765/65303466-b772ec80-dbb0-11e9-9e3a-35d2fd2efcf5.png)

**Comment by Reamer** [comment]
I have no idea, what you mean with "dependency-check badge".
In prior version (for sonarqube 5.x) this plugin contained a dependency-check widget. Custom widgets are not supported anymore in sonarqube 6.x and above, therefore we removed this widget.

As I can see in your screenshot you have recognized the Dependency-check page under "more".

**Comment by leizhen** [comment]
Got it,thanks. The issue i opened is not a defect.

**Comment by Reamer** [comment]
Okay, so i close this issue
