### ISSUE TITLE
Metrics direction wrong (IRS/VCR)

### ISSUE THREAD

**Issue by RolphH** [dependency-check/dependency-check-sonar-plugin#178]
I believe the Metrics direction for Inherited Risk Score and Vulnerable Component Ratio are set wrong.

**Current behavior**
When trying to add those to the Sonar Quality Gate, it shows the error rate is below X, instead of error rate is above X.

![Screen Shot 2019-10-03 at 13 58 31](https://user-images.githubusercontent.com/10166243/66132838-fadc4a80-e5f5-11e9-86dc-ae745bed1c0f.png)

**Expected behavior**
I expect the Quality Gates fails when the ratio is above the specified error, not below (as lower is better). Same goes for Inherited Risk Score (lower is better).

**Versions:**
-   dependency-check: 5.2.1
-   sonarqube: 7.9.1
-   dependency-check-sonar-plugin: 1.2.5

**Comment by Reamer** [comment]
You are right. I'll change this.
