### ISSUE TITLE
align sonar quality gate to dependency check quality gate

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/dependency-check-sonar-plugin#179]
**Describe the bug**
Dependency check quality gate and Sonar dependencies quality gates are not aligned

**To Reproduce**
Run a dependency check scan against an app with two vulnerabilities that you accept. In dependency check, you can change your threshold to "accept" vulnerabilities with false positives, but, when using this plugin, there is no option to mark those as false positives. All the issues coming from dependency check are considered as vulnerabilities under "Using Components with Known Vulnerabilities"

Is there any way to ignore those dependency check false positives in sonar apart from doing it manually one by one?

Thanks

**Comment by Reamer** [comment]
Hi @javixeneize,
can you point me to the configuration option, where dependency-check will accept vulnerabilities with false positives by a threshold.
In general this plugin should ignore vulnerabilities, which are suppressed by dependency-check via [`--suppression`](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)

**Comment by javixeneize** [comment]
Hi

Yes, suppression is one of this, but there is another way of setting the quality gate, at least in the jenkins plugin

https://wiki.jenkins.io/display/JENKINS/OWASP+Dependency-Check+Plugin

I dont know if there is any way to do something similar in sonar to overwrite the existing quality gate in terms of dependency analysis.

Thanks

**Comment by Reamer** [comment]
Hi @javixeneize 
this plugin maps the cvss score to an sonarqube issue severity. At the moment sonarqube supports  five [issue severities](https://docs.sonarqube.org/latest/user-guide/issues/) e.g. info, minor, major, critical, blocker.
At the moment there is no possibility to ignore issues which are under a specific threshold, but 
you can configure the score <-> issue severity mapping. Checkout the [plugin configuration](https://github.com/dependency-check/dependency-check-sonar-plugin#plugin-configuration). `sonar.dependencyCheck.severity.minor/major/critical/blocker` should help you.

**Comment by javixeneize** [comment]
Ok. Thanks for the info :)
