### ISSUE TITLE
Compatibility with sonarqube 8.0

### ISSUE THREAD

**Issue by MartinForReal** [dependency-check/dependency-check-sonar-plugin#185]
**Is your feature request related to a problem? Please describe.**
The plugin is not listed on Sonarqube 8.0 market place

**Comment by Reamer** [comment]
This plugin is compatible with sonarqube 8.0.
You can install this plugin manually - [Installation](https://github.com/dependency-check/dependency-check-sonar-plugin#installation)
We are working for a sonarqube market place integration - https://github.com/dependency-check/dependency-check-sonar-plugin/issues/85

Closing in favor of https://github.com/dependency-check/dependency-check-sonar-plugin/issues/85
