### ISSUE TITLE
Incorrect assigning issues by Filename in pom.xml, when more than one pom.xml exist in project.

### ISSUE THREAD

**Issue by Kovshar-OS** [dependency-check/dependency-check-sonar-plugin#192]
Often, when plugin makes assigning issues inside pom.xml by Filename, and more than one pom.xml (parent pom and childs poms) exists in project, plugin makes incorrect assigning to wrong pom.xml.
Plugin version 1.1.4

Example of assign to wrong pom
\proj\proj1\pom.xml
![2](https://user-images.githubusercontent.com/37664383/70605911-0c4c5f00-1c04-11ea-9a33-13e3ddbde8e9.png)

Proper assignment should be there
\proj\proj2\pom.xml
![1](https://user-images.githubusercontent.com/37664383/70605930-166e5d80-1c04-11ea-9f33-2593714b6113.png)

**Comment by Reamer** [comment]
Can you provide an github example project, where I can test assigning?

**Comment by Kovshar-OS** [comment]
Hi, Reamer! I create simple project https://github.com/Kovshar-OS/fortest

**Comment by Reamer** [comment]
Hi @Kovshar-OS,
I worked with your example project. Made some changes to compile it successfully. PR: https://github.com/Kovshar-OS/fortest/pull/1

I can't reproduce you result with the current master of dependency-check-sonar-plugin. 
To reproduce my result:
```bash
git clone https://github.com/Reamer/fortest.git
cd fortest/relock/utrain
mvn clean package dependency-check:aggregate
mvn sonar:sonar -Dsonar.host.url=http://localhost:9000/ -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json
```

![sonar_dependency_check](https://user-images.githubusercontent.com/454320/70804416-be2b8d00-1db6-11ea-8e63-26415e40ffe5.png)

**Comment by Reamer** [comment]
Just saw, that you are using an old version. Please update the plugin to the newest version for your sonarqube.
Sonarqube 6 LTS isn't supported. So you should use plugin version 1.2.6.

**Comment by Kovshar-OS** [comment]
It's happens only when using sonar-scanner. I know that better way is to use sonar for maven in this case, but anyway can you check it when runnig with sonar-scanner?

**Comment by Reamer** [comment]
In general, there is no difference between sonar-scanner and maven. sonar-scanner is a wrapper script, that runs java and maven.
Anyway, I tested also your project also with sonar-scanner. There is no difference. **You are using the right plugin version?**

**Comment by Kovshar-OS** [comment]
I tested for plugin version 1.1.4, 1.1.5 with same result. 
I have Sonar 7.0, so plugin version 1.2.6 is not applicable.

**Comment by Reamer** [comment]
Hi @Kovshar-OS,
Sonarqube 7.0 isn't supported anymore. Please use newest version or latest LTS.

**Comment by Reamer** [comment]
You can test version 1.1.6 https://github.com/dependency-check/dependency-check-sonar-plugin/releases/tag/1.1.6
