### ISSUE TITLE
Breaking change when support for sonar.dependencyCheck.reportPath is dropped

### ISSUE THREAD

**Issue by pethers** [dependency-check/dependency-check-sonar-plugin#203]
**Describe the bug**
Breaking change when dropping support for sonar.dependencyCheck.reportPath is dropped in 2.0.0 release

**To Reproduce**
Run latest release with sonar.dependencyCheck.reportPath property set.

**Expected behavior**
Would prefer fallback to sonar.dependencyCheck.reportPath for xml report if sonar.dependencyCheck.xmlReportPath and sonar.dependencyCheck.jsoReportPath is missing.

**Versions (please complete the following information):**

-   dependency-check 5.3.0
-   sonarqube 7.9.2
-   dependency-check-sonar-plugin 2.0.0

**Additional context**
Have about 1000+ projects using sonar.dependencyCheck.reportPath, so breaking change to update to latest version of this plugin. So would make it a lot easier if fallback to old behavior was supported.

**Comment by pethers** [comment]
Could provide a pull request, but think below change would make migration more soft by deprecating old property instead of removing it directly.

`  public static XmlReportFile getXmlReport(Configuration config, FileSystem fileSystem, PathResolver pathResolver) throws FileNotFoundException {

String path;
String property
       if (!config.hasKey(DependencyCheckConstants.XML_REPORT_PATH_PROPERTY) &&
config.hasKey(DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY)) {
        path =config.get(DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY).get();
property=DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY;
LOGGER.info("Dependency-Check {} property for xml report is deprecated, please migrate to {]", DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY,DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY);
} else {
        path =config.get(DependencyCheckConstants.XML_REPORT_PATH_PROPERTY).orElse(DependencyCheckConstants.XML_REPORT_PATH_DEFAULT);
property=DependencyCheckConstants.XML_REPORT_PATH_PROPERTY;
}
        File report = pathResolver.relativeFile(fileSystem.baseDir(), path);
        report = checkReport(report, ReportFormat.XML, property);
        if (report == null) {
            throw new FileNotFoundException("XML-Dependency-Check report does not exist.");
        }
        return new XmlReportFile(report);
    }
`

**Comment by Reamer** [comment]
Hi @pethers,
please provide a PR. Please keep in mind, that all config parameters should have a default value. Therefore I think, I can not make the breaking change smooth.

**Comment by Reamer** [comment]
`config.hasKey(DependencyCheckConstants.XML_REPORT_PATH_PROPERTY)` should be always true, because of the default value.

**Comment by Reamer** [comment]
Hi @pethers,
I just realize that we have a key for "deprecated keys". https://github.com/dependency-check/dependency-check-sonar-plugin/pull/205/files#diff-1dcd5b15505370d5e1cd906092535c31R41

But I doesn't found a possibility to write a message to output, if the deprecated key is in use. Any ideas?

**Comment by pethers** [comment]
Thanks for the quick response, didn't know the deprecatedKey option did exist. 

But maybe enough to log it in the getXmlReport method. 

`
if (config.hasKey(DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY) {
LOGGER.info("Dependency-Check {} property for xml report is deprecated, please migrate to {]", DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY,DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY);
} 
`

Busy at work, but can test it later tonight at home.

**Comment by Reamer** [comment]
The following code outputs the warning every time.
```
        if (config.get(DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY).isPresent()) {
            LOGGER.warn("Dependency-Check property {} for xml report is deprecated, please migrate to {}.", DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY, DependencyCheckConstants.XML_REPORT_PATH_PROPERTY);
        }
```
Your possible solution doesn't output anything.
```
        if (config.hasKey(DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY)) {
            LOGGER.warn("Dependency-Check property {} for xml report is deprecated, please migrate to {}.", DependencyCheckConstants.DEPRECTED_XML_REPORT_PATH_PROPERTY, DependencyCheckConstants.XML_REPORT_PATH_PROPERTY);
        }
```

**Comment by Vampire** [comment]
I also stumbled upon this, but because I followed the readme where only the new key was documented, but in 1.1.6 still the old was used.
I'd like to suggest the following:
- if `sonar.dependencyCheck.reportPath` is defined, log a deprecation warning even if `sonar.dependencyCheck.jsonReportPath` is defined and thus the XML report would not be used anyway if the JSON report is present
- if `sonar.dependencyCheck.reportPath` and `sonar.dependencyCheck.xmlReportPath` are defined, use `sonar.dependencyCheck.xmlReportPath`
- if only `sonar.dependencyCheck.reportPath` is defined, use `sonar.dependencyCheck.reportPath`

Besides that, shouldn't the `sonar.dependencyCheck.jsonReportPath` be also used in `org.sonar.dependencycheck.DependencyCheckConfiguration.getPropertyDefinitions`?
