### ISSUE TITLE
Error at running Sensor Dependency-Check [dependencycheck]

### ISSUE THREAD

**Issue by Marco-Jojojo** [dependency-check/dependency-check-sonar-plugin#206]
name | about | title | labels | assignees
-- | -- | -- | -- | --
Bug report - DependencyCheck | Illegal character |   | bug |  

**Describe the bug:** Hello. I'm experiencing this:

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project xxx: Illegal char <*> at index 0: **/dependency-check-report.xml`

Looks like something similar to the issue in https://github.com/dependency-check/dependency-check-sonar-plugin/issues/49

**To Reproduce:**
Java 8 project.
Maven - Multimodule
Running the following in the parent module:
```
mvn sonar:sonar   -Dsonar.projectKey=project_key   -Dsonar.host.url=url   -Dsona
r.login=login_key
```
See error

**Current behavior:** [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project xxx: Illegal char <*> at index 0: **/dependency-check-report.xml

**Versions:** JDK 1.8.0_191, maven 3.0.4, sonar-maven-plugin:3.7.0.1746, SonarQube 7.9.1

Appreciate your help

**Comment by Reamer** [comment]
Please rewrite your bug to match this [template](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by Marco-Jojojo** [comment]
Done

**Comment by Marco-Jojojo** [comment]
Also run with Maven 3.6.3. Same issue.

**Comment by Reamer** [comment]
Can you reproduce your error with this [maven multi submodule](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-module-maven)?
Which version of dependency-check-sonar-plugin do you use?

**Comment by Reamer** [comment]
Please run with debug `-X` and print the stack trace.

**Comment by Marco-Jojojo** [comment]
```
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://xxx.nexus.xxx/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced
org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://xxx.nexus.xxx/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced
.......
[ERROR] No plugin found for prefix 'dependency-check' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (xxx)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'dependency-check' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories 
.......
```

So I added:

```
<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>5.3.0</version>
                <configuration>
                    <format>ALL</format>
                </configuration>
            </plugin>
```

Now it is working as expected. I didn't know I had to add owasp dependency explicitly. Otherwise it kept failing.

Thanks for your response.

**Comment by Reamer** [comment]
If your issue is solved, please close it.
