### ISSUE TITLE
Mention necessity for adding Gradle build scripts to sonar.sources in documentation

### ISSUE THREAD

**Issue by Vampire** [dependency-check/dependency-check-sonar-plugin#207]
I struggeled with the dependency check report being parsed properly and the measures showing the found vulnerabilities, but not having any entries for the issues.

I finally found out, that you need to manually add the Gradle build scripts to `sonar.sources` for the scanner to search through them for the dependency reasons.
This is nowhere mentioned, except for the Gradle examples, that this is necessary.
Please add this fact to the documentation.

**Comment by Reamer** [comment]
Hi @Vampire,
It would be great, if you open a PR for updating the documentation. Please consider other programming languages (nodejs) and build tools (maven).

**Comment by Reamer** [comment]
@Vampire Any thoughts from your site to make the documentation better?

**Comment by Vampire** [comment]
I think the changes in your PR are fine so far, at least it is explicitly mentioned then. :-)
