### ISSUE TITLE
Non-standard named Gradle build scripts are not considered as dependency reasons

### ISSUE THREAD

**Issue by Vampire** [dependency-check/dependency-check-sonar-plugin#208]
We have about 50 sub-projects in our Gradle build.
Having all Gradle build scripts named `build.gradle` is very inconvenient if you want to open a specific one in the IDE.
Because of that we use the Gradle feature that you can freely define the build scripts name in `settings.gradle` by setting `Project#buildFileName`.
For us this looks in `settings.gradle` like
```groovy
def setBuildFileNameRecursively
setBuildFileNameRecursively = { it ->
   it.buildFileName = "${it.name}.gradle"
   it.children.each { setBuildFileNameRecursively it }
}
setBuildFileNameRecursively rootProject
```
which names the build script after the actual project name.

Your scanner unfortunately only considers `build.gradle` and `build.gradle.kts` as valid dependency reasons.

Instead it should consider `*.gradle` and `*.gradle.kts`.

After I changed the dependency reason searcher to
```java
String[] gradlePathPatterns = {"**/*.gradle", "**/*.gradle.kts"};
Iterable<InputFile> buildGradles = context.fileSystem().inputFiles(context.fileSystem().predicates().matchesPathPatterns(gradlePathPatterns));
```
it worked fine, recognizing the issues in the build scripts.

**Comment by Reamer** [comment]
Hi @Vampire,
thanks reviewing the code. It would be great, if you open a PR.
