### ISSUE TITLE
Issues created for suppressed vulnerabilities in 2.0.1

### ISSUE THREAD

**Issue by pethers** [dependency-check/dependency-check-sonar-plugin#209]
**Describe the bug**
Issues created for suppressed vulnerabilities, the html report displays suppressed issues https://www.hack23.com/sonar/project/extension/dependencycheck/report?id=com.hack23.cia%3Acia-all&qualifier=TRK but issues are created https://www.hack23.com/sonar/project/issues?id=com.hack23.cia%3Acia-all&resolved=false&rules=OWASP%3AUsingComponentWithKnownVulnerability&types=VULNERABILITY

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install dependency-check version 2.0.1
2. Run owasp report using version 5.3.0 and run sonar scanner plugin
3. Login to https://www.hack23.com/sonar/project/extension/dependencycheck/report?id=com.hack23.cia%3Acia-all&qualifier=TRK and see suppressed vulnerabilities
4. See error with issues created at https://www.hack23.com/sonar/project/issues?id=com.hack23.cia%3Acia-all&resolved=false&rules=OWASP%3AUsingComponentWithKnownVulnerability&types=VULNERABILITY

**Current behavior**
Issues created for some of the suppressed issues.

**Expected behavior**
Only create issues for non suppressed issues.

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check 5.30
-   sonarqube 7.9.2
-   dependency-check-sonar-plugin 2.0.1

**Additional context**
Not sure if this is associated with dependency-check 5.3.0 or the latest version of the sonar-plugin. 
Can do some test the next few days to check 5.2.4 version of dependency-check, to check if the format or any strings has been changed.

best regards

**Comment by Reamer** [comment]
Hi @pethers,
I can reproduce your problem. Working on a fix.

**Comment by Reamer** [comment]
Hi @pethers,
please compile the plugin on [branch parser_exception_210] yourself(https://github.com/dependency-check/dependency-check-sonar-plugin/tree/parser_exception_210) and give me feedback if it fix your issue.

**Comment by pethers** [comment]
will give it a test in the morning, thanks for the rapid response!

**Comment by pethers** [comment]
Have tested the https://github.com/dependency-check/dependency-check-sonar-plugin/tree/parser_exception_210 , and works as expected now https://www.hack23.com/sonar/component_measures?id=com.hack23.cia%3Acia-all&metric=total_vulnerabilities :+1:

**Comment by Reamer** [comment]
Thanks for feedback. Waiting also for feedback in #210. After that I'll make a bugfix release.
