### ISSUE TITLE
Preferred format? JSON or XML?

### ISSUE THREAD

**Issue by TobiX** [dependency-check/dependency-check-sonar-plugin#214]
**Is your feature request related to a problem? Please describe.**
Currently, the documentation isn't clear why one should specify the XML & JSON report files. Is one better then the other? Are both used/required? From the source I could see that the JSON report is preferred over the XML report. Is that a concision decision? Fair dice roll?

**Describe the solution you'd like**
Reword the documentation to at least match the code (JSON is tried before XML) or even better mention a clear preference for one or the other. If both are equally supported, make the "file not found" message less scary (Currently, you get `JSON-Analysis skipped/aborted due to missing report file` even if an XML file is found afterwards, which reads like an error because of the word `aborted`) or even restructure the whole error handling in `DependencyCheckSensor.parseAnalysis` so that non-fatal problems are clearly distinguished from fatal problems (e.g. neither JSON nor XML is present/could be parsed).

**Comment by Reamer** [comment]
@TobiX Any thoughts from your site to make the documentation better?

**Comment by TobiX** [comment]
Thanks, that proposed change indeed addresses my problems!
