### ISSUE TITLE
sonarqube show warning about package-lock.json

### ISSUE THREAD

**Issue by thib3113** [dependency-check/dependency-check-sonar-plugin#222]
**Describe the bug**
When I run sonar scanner, I see this warning : 

`INFO: We doesn't found any Project configuration file e.g. pom.xml, gradle.build, build.gradle.kts, package-lock.json and can not link dependencies`

In fact, I doesn't really know what the warning try to say, because just after I see : 
`INFO: Linking 27723 dependencies to project`

**Versions (please complete the following information):**

-   dependency-check : 5.3.0
-   sonarqube : 8.0.0
-   dependency-check-sonar-plugin : 2.0.3-snapshot (but same warning on 2.0.2)

**Additional context**
I try this on the sonar-project.properties : 
`sonar.sources=src,package-lock.json`
and 
`sonar.sources=src`
but same warning ...

Any idea where to find more informations ...

**Comment by Reamer** [comment]
Hi @thib3113,
the plugin tries to link all SonarQube issues to files, because only then the are unique and can be managed (e.g. _"resolved as ..."_) in sonarqube UI.
So it's quite important that the plugin finds project configuration files like pom.xml package-lock.json and so on.
`sonar.sources=src,package-lock.json` should work. Let me test our [examples/single-module-nodejs project](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/single-module-nodejs)

**Comment by Reamer** [comment]
I checked with provided [examples/single-module-nodejs project](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/single-module-nodejs).
`sonar.sources=src,package-lock.json` works for me.
Run sonarScanner in debug mode `sonar-scanner -X`. `package-lock.json` should be indexed.
```
10:48:49.089 DEBUG: readpipe [git, --version],/usr/bin
10:48:49.096 DEBUG: readpipe may return 'git version 2.17.1'
10:48:49.096 DEBUG: remaining output:

10:48:49.096 DEBUG: readpipe [git, config, --system, --edit],/usr/bin
10:48:49.104 DEBUG: readpipe may return '/etc/gitconfig'
10:48:49.104 DEBUG: remaining output:

10:48:49.140 DEBUG: 5 non excluded files in this Git repository
---> 10:48:49.149 DEBUG: 'package-lock.json' indexed with language 'null'  <----
10:48:49.150 INFO: 1 file indexed
10:48:49.150 INFO: 0 files ignored because of scm ignore settings
```

**Comment by thib3113** [comment]
So, I can finally run my CI ( babel upgrade, nothing build, some fun today ), and I see this : 
`/package-lock.json' is excluded by the scm ignore settings.` 😠 .... 

So, I will try to disable the scm exclusion, or adding the package-lock.json

**Comment by Reamer** [comment]
package-lock.json should/must be part of your scm. It's advise be npm https://docs.npmjs.com/configuring-npm/package-lock-json.html
> This file is intended to be committed into source repositories, and serves various purposes:

**Comment by thib3113** [comment]
@Reamer yes, in theory ...
In pratice, our company use a private npm registry with an IP whitheliste, so a développer working at home need to use the npm registry, and manually copy some private node_modules, so each npm install generate a package-lock with totally différent url .

And the CI server run at my office (not the head quarter), with a really Bad connexion, so I use a "cache npm registry", so one more différent url for the registry .

Yes I know we need to commit the package-lock, but need to do a script to update it each Times, or just doesn't commit it

**Comment by Reamer** [comment]
I hope you find a way to solve your issue. I will close this issue because we have found the reason. It would be nice if you share your solution with a short comment.

**Comment by thib3113** [comment]
My solution was : 
 - add -X to sonar-scanner to see debug
 - see this line `/package-lock.json' is excluded by the scm ignore settings.` (because I add package-lock.json in .gitignore)
 - add this option `sonar.scm.exclusions.disabled=true` (this disabled the check of files in .gitignore)
