### ISSUE TITLE
where is the ${WORKSPACE}?

### ISSUE THREAD

**Issue by wangzhengqing** [dependency-check/dependency-check-sonar-plugin#224]
when finished job on jenkins with reports. sonar can't find the report file.sonar.dependencyCheck.htmlReportPath=${WORKSPACE}/dependency-check-report.html.                   where is the ${WORKSPACE}? or just don't write it?

**Comment by Reamer** [comment]
${WORKSPACE} should be an environment variable which should be available in the Jenkins build context.
You can overwrite the default path. Take a look at our examples, e.g [single-module-maven](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/examples/single-module-maven/pom.xml#L21-L23)
