### ISSUE TITLE
Unable to push report to SonarQube server when integrating with dependencyCheck plugin

### ISSUE THREAD

**Issue by x80486** [dependency-check/dependency-check-sonar-plugin#226]
## Describe the bug

I'm currently using the Gradle plugin as:

```groovy
import org.owasp.dependencycheck.reporting.ReportGenerator

plugins {
  id "org.owasp.dependencycheck" version "5.3.0"
  id "org.sonarqube" version "2.7"
}

dependencies() {
    compileOnly("org.owasp:dependency-check-gradle:5.3.0")
}

dependencyCheck {
  analyzers {
    assemblyEnabled = false
    nodeEnabled = false
  }
  failOnError = false
  formats = [ReportGenerator.Format.HTML, ReportGenerator.Format.XML]
}

sonarqube {
  properties {
    property "sonar.dependencyCheck.htmlReportPath", "build/reports/dependency-check-report.html"
    property "sonar.dependencyCheck.reportPath", "build/reports/dependency-check-report.xml" // <- Big time with this one
    property "sonar.dependencyCheck.xmlReportPath", "build/reports/dependency-check-report.xml"
    property "sonar.projectDescription", "${project.description}"
    property "sonar.projectKey", "tld.domain:${project.name}"
    property "sonar.projectName", "tld.domain::${project.name}"
  }
}
```

I therefore execute this as: `./gradlew -Dsonar.host.url=https://reports.domain.tld/sonarqube -Dsonar.login=token dependencyCheckAnalyze sonarqube --info`. Everything is fine until the point it's trying to upload the results to the server:

```shell
> Task :sonarqube FAILED
Sensor JavaSquidSensor [java] (done) | time=220668ms
Sensor PmdSensor [pmd]
Sensor PmdSensor [pmd] (done) | time=1ms
Sensor SurefireSensor [java]
parsing [/path/to/project/build/test-results/test]
Sensor SurefireSensor [java] (done) | time=62ms
Sensor Removed properties sensor [java]
Sensor Removed properties sensor [java] (done) | time=1ms
Sensor JavaXmlSensor [java]
Sensor JavaXmlSensor [java] (done) | time=3ms
Sensor HTML [web]
Sensor HTML [web] (done) | time=6ms
Sensor Dependency-Check [dependencycheck]
Process Dependency-Check report
Process Dependency-Check report (done) | time=139ms
:sonarqube (Thread[Daemon worker,5,main]) completed. Took 3 mins 53.184 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> java.lang.NullPointerException (no error message)
```

I know for sure that this setting: `property "sonar.dependencyCheck.reportPath", "build/reports/dependency-check-report.xml"` is what's causing that `java.lang.NullPointerException (no error message)`. On the other hand, if I don't use it, the action is successfully executed, but nothing is uploaded to the SonarQube server.

## To Reproduce

1. Grab one of the example projects with Gradle
2. Modify the `dependencycheck` version to `5.3.0` and the SonarQube plugin version to `2.7`
3. Execute `dependencyCheckAnalyze` and `sonarqube` tasks with the options to identify the location to a SonarQube server and the token needed to upload the result(s)

## Current behavior

The action(s) fail with a `java.lang.NullPointerException (no error message)`.

## Expected behavior

To be able to complete the report(s) and upload the results successfully.

## Versions (please complete the following information)

-  dependency-check: `5.3.0`
-  sonarqube: `2.7`
-  dependency-check-sonar-plugin: `5.3.0`

**Comment by TobiX** [comment]
Can you try with either:
1. My fix for 5.3.0 (pull #227)
2. Use DependencyCheck 5.2.4 for now

I believe this might be an incompatibility in the report format

**Comment by Reamer** [comment]
Hi @x80486,
#230 or #229 should fix your issue. I have also updated all examples, doesn't found any more issues with DependencyCheck 5.3.0

**Comment by x80486** [comment]
All right! Thanks for the follow up. I'm going to update to version `5.3.0` and give it another whirl...if I find something I'll update this ticket (or create a new one), otherwise (everything is OK and) no further chatting is needed :sunglasses:
