### ISSUE TITLE
When will version 2.0.3 be available through SonarQube Marketplace?

### ISSUE THREAD

**Issue by oetlinge** [dependency-check/dependency-check-sonar-plugin#233]
Currently running OWASP dependency check and trying to upload the JSON reports to our SonarQube instance fails with an error about 'unscored' not an ignorable field. Noticed in the release notes that this issue is fixed in version 2.0.3 of the plugin, but I don't see it listed in the marketplace yet.

Our test environment:
SonarQube 8.2.0.32929
Dependency Check 5.3.0 (command line tool)
Dependency Check plugin 2.0.2

**Comment by Reamer** [comment]
I have already a PR open to update via marketplace.
https://github.com/SonarSource/sonar-update-center-properties/pull/104
