### ISSUE TITLE
SonarQube shows vulnerabilities for wrong file

### ISSUE THREAD

**Issue by bigstinky86** [dependency-check/dependency-check-sonar-plugin#247]
We've got an issue with dependency check sonar plugin. After gradle build with gradle dependecy check plugin SonarQube shows the next;

![image](https://user-images.githubusercontent.com/41194602/78982929-f8c6eb80-7b44-11ea-9cd8-b300d10748d7.png)

It shows that file UI/package-lock.json contains this vulnerabilities but in fact there is no such jar is mentioned. Yes we use this jar as a dependency in our project but it is specified in build.gradle as dependecy but not in UI/package-lock.json

-  dependency-check-gradle 5.3.0
-  dependency-check-sonar-plugin 2.0.4

Please advise.

**Comment by bigstinky86** [comment]
There are mentions about httpclient, guava and log4j. We will definitely update them but the bug should be fixed

**Comment by Reamer** [comment]
@bigstinky86 
Can you reproduce your issue with the changes from PR #257?

**Comment by bigstinky86** [comment]
I'll come back in a few days with outcome.

**Comment by bigstinky86** [comment]
Hello,

Unfortunately it still shows vulnerabilities in UI/package-lock.json

**Comment by Reamer** [comment]
Hi @bigstinky86,
can you provide the following information.
 - file tree of your project configuration files e.g. *.gradle, package-lock.json
 - whole dependency part out of your report
 - debug output of `gradle sonarqube`
