### ISSUE TITLE
"We doesn't found any Project configuration file e.g. pom.xml, gradle.build, build.gradle.kts, package-lock.json and can not link dependencies"

### ISSUE THREAD

**Issue by alixwar** [dependency-check/dependency-check-sonar-plugin#248]
**Describe the bug**
I'm not able to report properly. While troubleshooting I stumble on this error log message:

"We doesn't found any Project configuration file e.g. pom.xml, gradle.build, build.gradle.kts, package-lock.json and can not link dependencies"

In Gradle the files are not named "gradle.build" but "build.gradle". So I guess the logic is flawed as well to detect these config files.

**Versions (please complete the following information):**
I have a Gradle Android multi-module project

-   dependency-check
5.3.0
-   sonarqube
8.2.0
-   dependency-check-sonar-plugin
2.0.4

**Comment by Reamer** [comment]
Hi @alixwar 
The log message is a typo. Thanks for giving me this hint. I'll fix that.
As you can see in the [source code](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/350e011e79afecd7592506c820f461d054ed74cb/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java#L63) `"**/*.gradle` and `**/*.gradle.kts` is our current pattern.
Please check that your project configuration file is part of [`sonar.sources`](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/350e011e79afecd7592506c820f461d054ed74cb/examples/single-module-gradle/build.gradle#L39). Take a look into our gradle example project.

**Comment by alixwar** [comment]
@Reamer Thanks for the pointer. I'm sure you are right about this. I just noticed the warning and didn't bother to look into the source code. I will close this issue for now and re-open only if this is still an issue.
