### ISSUE TITLE
SonarQube doesn't display dependency check results

### ISSUE THREAD

**Issue by crispadaro74** [dependency-check/dependency-check-sonar-plugin#253]
SonarQube doesn't show the dependency check result page, it stays empty.

There is an error in the web browser console:
Request: **<baseurl>/api/measures/component?componentKey=TestProject&metricKeys=report**
Response: **{"errors":[{"msg":"The 'component' parameter is missing"}]}**

The request was triggered by:
**<baseurl>/project/extension/dependencycheck/report?id=TestProject&qualifier=TRK**

The JS error is triggered in this point:
_submit(): Promise<Response> {
    const { url, options } = this.getSubmitData({ ...getCSRFToken() });
    return window.fetch(((window as any).baseUrl as string) + url, options);
  }_

Versions:

- sonarqube 8.1.0.31237
- dependency-check-sonar-plugin 2.0.2

**Comment by Reamer** [comment]
Hi @crispadaro74 
please update to the [newest release](https://github.com/dependency-check/dependency-check-sonar-plugin/releases).
We have done a complete rewrite of the dependency check result page. For more information checkout https://github.com/dependency-check/dependency-check-sonar-plugin/pull/219
