### ISSUE TITLE
Dependency-Check menu item missing in branches view

### ISSUE THREAD

**Issue by Sebbl22** [dependency-check/dependency-check-sonar-plugin#254]
**Describe the bug**
The "Dependency-Check" menu item is not present in any branch, except "master". I don't know if it should be visible, but I would expect it, since analysis can be done on a per-branch basis in SonarQube (Developer Edition and upwards).

**To Reproduce**
1. Analyze a non-main branch (develop, feature/xyz, ...)
2. Set ```sonar.dependencyCheck.htmlReportPath``` and ```sonar.dependencyCheck.jsonReportPath```

**Current behavior**
- "Dependency-Check" menu item is only present in the main-branch (master)
- Annotations from the jsonReportPath are processed

**Expected behavior**
"Dependency-Check" menu item is present in every branch

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10319545/80365410-d42e7b80-8887-11ea-93b7-d9460e151091.png)

![grafik](https://user-images.githubusercontent.com/10319545/80365425-dabcf300-8887-11ea-9cd6-7a3b3d402f26.png)

**Versions:**

-   dependency-check Azure DevOps Plugin 5.3.2.3
-   sonarqube 8.2.0.32929 Developer Edition on-premise
-   dependency-check-sonar-plugin 2.0.4

**Comment by Reamer** [comment]
Hi @Sebbl22,
branch view is not free of charge, so it can not be supported. If SonarQube has changed this behavior, please reopen this ticket.

**Comment by ralgozino** [comment]
Hello!

Sorry to hijack the issue :) we are using an [opensource plugin ](https://github.com/mc1arke/sonarqube-community-branch-plugin) that enables the Multi Branch Analysis enabling also the branch selector dropdown, we would really like the dependency check for other branches than master if possible.
