### ISSUE TITLE
Dependency check result for a branch is not displayed in Sonar

### ISSUE THREAD

**Issue by ahorvath23** [dependency-check/dependency-check-sonar-plugin#260]
**Describe the bug**
The result of the OWASP Dependency-Check plugin for a branch is not displayed in Sonar.

Versions:
dependency-check 5.3.2
docker.io/sonarqube:8.2-enterprise version

**To Reproduce**
1. Install Sonar
2. Install dependency-check plugin in Jenkins
3. Configure dependency-check plugin among Jenkins tools
4. Clone benchmark project: https://github.com/OWASP/Benchmark
5. Create branch
6. Implement pipeline with the the following steps: dependencyCheck additionalArguments: '--format XML --out dependency-check-report.xml', odcInstallation: '5.3.2' and dependencyCheckPublisher pattern: 'dependency-check-report.xml'
7. Open project in Sonar
8. The dependency check report is not shown

**Current behavior**
The report is generated correctly. Based on the Jenkins log the HTML report is published, but the report is not displayed in Sonar.

**Expected behavior**
The dependency check report should be displayed as in case of master.

**Screenshots**
See the screenshots about the Jenkins log and the Sonar screen.
![Jenkins-log](https://user-images.githubusercontent.com/29041445/81606784-ef46d280-93d3-11ea-8e01-fb5012bff4c4.PNG)
![Sonar_branch](https://user-images.githubusercontent.com/29041445/81606790-f2da5980-93d3-11ea-999d-872bede8ab25.png)
![Sonar_master](https://user-images.githubusercontent.com/29041445/81606795-f40b8680-93d3-11ea-95b0-a570a18febca.png)

**Versions (please complete the following information):**
-   sonarqube: docker.io/sonarqube:8.2-enterprise version
-   Jenkins OWASP Dependency-Check Plugin 5.3.2
-  Sonar Dependency-Check plugin 2.0.4

**Additional context**
The result of the dependency check of the master is published and displayed correctly with the same Jenkins pipeline code, so the problem exists with the branches only.

**Comment by Reamer** [comment]
Hi @ahorvath23 
as mentioned in #254 I'm not able to verify code changes without a commercial version.

Some technical code reasons, why it doesn't work.
1)
Currently we use the [`/api/measures/component` API](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/ddcc4eca0aace387027af7386a5080ee029b8eeb/sonar-dependency-check-plugin/src/main/js/report_page/components/DependencyCheckReportApp.js#L27-L30) to get the HTML report. This API endpoint does not support branches. Maybe the API will be extended with a commercial version.
![sonarqube_8_2_api](https://user-images.githubusercontent.com/454320/81647725-c94e1c00-942d-11ea-8809-b356aafc04b8.png)

2)
In the file [DependencyCheckReportPage.java](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/page/DependencyCheckReportPage.java) we define where the page should be displayed.

Currently we use `Page.Qualifier.PROJECT` and `Page.Qualifier.MODULE`. There are [more available](https://github.com/SonarSource/sonarqube/blob/a879519f3993b60c0409a38a6ef50844e8327081/sonar-plugin-api/src/main/java/org/sonar/api/web/page/Page.java#L85-L109), but without testing I will not add qualifiers.
