### ISSUE TITLE
Support for Gradle multi module project (no aggregation)

### ISSUE THREAD

**Issue by alixwar** [dependency-check/dependency-check-sonar-plugin#261]
**Is your feature request related to a problem? Please describe.**
I have a Gradle project with multiple submodules. I am successfully generating XML reports for each individual module.

**Describe the solution you'd like**
I would like this setup to work:

build.gradle:
``` 
subprojects {
    sonarqube {
        properties {
            property "sonar.dependencyCheck.xmlReportPath", "$buildDir/reports/dependency-check-report.xml"
        }
    }
    apply plugin: 'org.owasp.dependencycheck'

    dependencyCheck {
        format 'XML'
    }
}
```
**Describe alternatives you've considered**
I got this setup to work before by aggregating the reports but it would be good if the plugin could handle the per-module reports.

**Additional context**

**Comment by alixwar** [comment]
Hmmm. Perhaps this feature request belongs to the OWASP dependency check plugin project...

**Comment by alixwar** [comment]
Never mind. The aggregate works fine...

**Comment by kolesaev** [comment]
Thanks @Reamer, it solved my issue
