### ISSUE TITLE
`Invalid value of sonar.sources` error after adding package-json.lock in the property as suggested by your README

### ISSUE THREAD

**Issue by khteh** [dependency-check/dependency-check-sonar-plugin#265]
With reference to your README: `This plugin tries to add SonarQube issues to your project configuration files (e.g. pom.xml, *.gradle, package-json.lock). Please make sure, that these files are part of sonar.sources.`, I add package-json.lock in the `sonar.sources` property and Jenkins build fails with the following message:
```
ERROR: Invalid value of sonar.sources for nodejs-testrestapi
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2.788s
INFO: Final Memory: 8M/235M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
ERROR: The folder 'package-json.lock' does not exist for 'nodejs-testrestapi' (base directory = 
```
`"sonar.sources": "BusinessLogic, routes, bin, app.js",`

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install '...'
2. Run '....'
3. Login to '....'

**Current behavior**
A clear and concise description of what happen currently.

**Expected behavior**
Works as suggested in *your* README!

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check
-   sonarqube
-   dependency-check-sonar-plugin

**Additional context**

**Comment by Reamer** [comment]
@khteh Have you taken a look at our [sample project nodejs](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/single-module-nodejs)?

**Comment by khteh** [comment]
What should I see there? I use `"sonarqube-scanner": "^2.6.0"` and have the sonar properties defined in `analyse.js` which is used to run sonar scanning.

**Comment by Reamer** [comment]
Based on https://community.sonarsource.com/t/java-io-filenotfoundexception-dependency-check-report-does-not-exist/26882/10 you used plugin version is very old.
Closed, because you doesn't provide a dependency-check-sonar-plugin version nor an SonarQube version.
