### ISSUE TITLE
sonar scan is stuck at this plugin if ${WORKSPACE}/dependency-check-report.foo is not present

### ISSUE THREAD

**Issue by khteh** [dependency-check/dependency-check-sonar-plugin#266]
I am using `"sonarqube-scanner": "^2.6.0"` for my Node.JS application. Sonarqube scanning is stuck at this plugin when there is no `${WORKSPACE}/dependency-check-report.foo` present in the file system. I am not sure why this is compulsory to use sonarqube scanning and report the issue here as a bug. https://community.sonarsource.com/t/java-io-filenotfoundexception-dependency-check-report-does-not-exist/26882

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install '...'
2. Run '....'
3. Login to '....'

**Current behavior**
A clear and concise description of what happen currently.

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check
-   sonarqube: `"sonarqube-scanner": "^2.6.0"`
-   dependency-check-sonar-plugin

**Additional context**

**Comment by Reamer** [comment]
Based on https://community.sonarsource.com/t/java-io-filenotfoundexception-dependency-check-report-does-not-exist/26882/10 the plugin version you are using is very old.
Closed, because you doesn't provide a dependency-check-sonar-plugin version nor an SonarQube version.
