### ISSUE TITLE
SonarQube scanner stops with Metric 'critical_severity_vulns' should not be computed by a Sensor error

### ISSUE THREAD

**Issue by charlesk40** [dependency-check/dependency-check-sonar-plugin#269]
**Describe the bug**
SonarQube scanner stops with Metric 'critical_severity_vulns' should not be computed by a Sensor error
See the error below.

`
00:03:15 INFO: Sensor CheckstyleSensor [checkstyle] (done) | time=126ms 00:03:15 INFO: Sensor Dependency-Check [dependencycheck] 00:03:15 INFO: Process Dependency-Check report 00:03:15 INFO: We doesn't found any Project configuration file e.g. pom.xml, gradle.build and can not link dependencies 00:03:15 INFO: Linking 9 dependencies to project 00:03:15 INFO: ------------------------------------------------------------------------ 00:03:15 INFO: EXECUTION FAILURE 00:03:15 INFO: ------------------------------------------------------------------------ 00:03:15 INFO: Total time: 12.443s 00:03:15 INFO: Final Memory: 38M/555M 00:03:15 INFO: ------------------------------------------------------------------------ 00:03:15 ERROR: Error during SonarQube Scanner execution 00:03:15 ERROR: Metric 'critical_severity_vulns' should not be computed by a Sensor 00:03:15 ERROR
`
**To Reproduce**
Install SonarQube server, scanner and sonar-dependency-check-plugin from the list of versions below.
Use the following properties in sonar-project.properties to set the dependecy check reports.

```
sonar.dependencyCheck.reportPath=target/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html

```
Run the org.owasp:dependency-check-maven:5.3.2 to produce dependency-check-report.xml and dependency-check-report.html and run the SonarQube Scanner.

SonarQube Scanner fails with Metric 'critical_severity_vulns' should not be computed by a Sensor error.

**Current behavior**
SonarQube Scanner fails.

**Expected behavior**
SonarQube Scanner should not fail.

**Versions (please complete the following information):**

```
SonarQube Scanner 3.3.0.1492
SonarQube server 8.4.0
https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.5/sonar-dependency-check-plugin-2.0.5.jar
org.owasp:dependency-check-maven:5.3.2

```

**Comment by Reamer** [comment]
Hi @charlesk40 
Are you sure that you have installed the plugin version 2.0.5?
With 2.0.5 the output should be:

https://github.com/dependency-check/dependency-check-sonar-plugin/blob/18e62512fc7cad6f1fe8b4635a2a909dc75e665c/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java#L118

**Comment by charlesk40** [comment]
Ah,  I just verified that we were actually using an older version. (Deployment to the latest is still in progress)
We will update to 2.0.5 and report back.
Thanks for that information.

**Comment by charlesk40** [comment]
2.0.5 indeed works great!
