### ISSUE TITLE
"This request cannot be processed. Try again later." in Security Hotspots view after importing report when "sonar.dependencyCheck.securityHotspot" is enabled.

### ISSUE THREAD

**Issue by alixwar** [dependency-check/dependency-check-sonar-plugin#270]
**Describe the bug**
The Security Hotspots view "crashes" when the option "sonar.dependencyCheck.securityHotspot" is enabled after importing issues from an OWASP dependency check report. It works fine importing the issues if the option is disabled.

I first saw the issue here: https://github.com/dependency-check/dependency-check-sonar-plugin/pull/252#issuecomment-617071057 but we couldn't figure out where the problem was. 
Since then the PR was merged and there was a new release (2.0.5) and I could reproduce the problem in production.
I created a support ticket at SonarSource for the problem and they say the following:

> I did look at your screenshot as indeed it is a JS/TS error.
> 
> But if the problem does not happen when the dependency check plugin is not installed, this is a side effect of that 3rd party plugin and there is not much I can do for you about it.
> 
> Regards, Olivier
> 
> PS: Admittedly we could have the JS code more robust to plugins that do not implement all the latest features of SonarQube (like hotspots, precise issue location - I suspect this is more due to the latter), but this can't be considered a priority issue for us.

The screenshot from the debugger that I sent to SonarSource: 
![SUPPORT-19786](https://user-images.githubusercontent.com/5415786/88542763-3d549500-d017-11ea-8a1f-ac2121db9004.jpg)

**Versions (please complete the following information):**
- Dependency check plugin 2.0.5
- SonarQube 8.3.1 Enterprise Edition

**Comment by Reamer** [comment]
Hi @alixwar,
as long as you can't provide a way to reproduce the problem, I can't help you. I'm sorry.

One last possibility:
If you disable the dependency-check hotspot feature and reimport your issues. Are all issue linked against a file?

**Comment by alixwar** [comment]
> Hi @alixwar,
> as long as you can't provide a way to reproduce the problem, I can't help you. I'm sorry.

I understand. But anyway, I think it's good that the issue is reported so that other people can provide input. 
 
> One last possibility:
> If you disable the dependency-check hotspot feature and reimport your issues. Are all issue linked against a file?

I can't play around with our production environment unfortunately so I would need to set up a sandbox. I'm not sure if/when I have time to look into this. But if/when I will post my results here.

**Comment by alixwar** [comment]
Here is one more screenshot with the line of code failing:

![issue-securityhotspot](https://user-images.githubusercontent.com/5415786/88791113-7d438580-d199-11ea-98ff-d1ab32492b40.jpg)

**Comment by alixwar** [comment]
FYI: I created a public bug report here: https://community.sonarsource.com/t/security-hotspots-report-broken-after-importing-issues-from-owasp-dependency-check/28818

**Comment by alixwar** [comment]
![issue-securityhotspot2](https://user-images.githubusercontent.com/5415786/88806591-ea164a00-d1b0-11ea-9296-46bbf6a7b411.jpg)
With debug info

**Comment by Reamer** [comment]
Hi @alixwar,
Thank you for opening a bug report in the sonarqube community forum and for providing debug output. It seems that the TypeScript did not find any TextRange. This can happen when a security hotspot issue is [linked to the project](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/8641f0aab93e149001087bcc172eed9ece81f80b/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java#L178-L192).

Do you have the [following output](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/8641f0aab93e149001087bcc172eed9ece81f80b/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java#L118) in your sonar analysis?
> No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.

**Comment by alixwar** [comment]
Hi @Reamer, yes I can confirm that I see this:

`2020-07-30T08:58:19.162+0200 [INFO] [org.sonarqube.gradle.SonarQubeTask] Using XML-Reportparser
2020-07-30T08:58:19.512+0200 [INFO] [org.sonarqube.gradle.SonarQubeTask] No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.`

**Comment by Reamer** [comment]
HI @alixwar,
this line should solve your problem.
https://github.com/dependency-check/dependency-check-sonar-plugin/blob/8641f0aab93e149001087bcc172eed9ece81f80b/examples/single-module-gradle/build.gradle#L39

**Comment by alixwar** [comment]
> HI @alixwar,
> this line should solve your problem.
> https://github.com/dependency-check/dependency-check-sonar-plugin/blob/8641f0aab93e149001087bcc172eed9ece81f80b/examples/single-module-gradle/build.gradle#L39

Thanks! I have a multi-module project but I will try this

**Comment by alixwar** [comment]
@Reamer This didn't work for a multi-module project but this configuration solved it for me:

```
property "sonar.sources", "src/main,build.gradle"
```
