### ISSUE TITLE
New XSD Version in ODC-6.0.0-snapshot

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/dependency-check-sonar-plugin#273]
While I do not believe the to-be-released changes will cause an issue for the sonar plugin I thought I should check. Please see https://github.com/jeremylong/DependencyCheck/pull/2781 - a new XSD will be published with 6.0.0. The new schema adds a few elements to the CVSS scores. I see that an older XSD is referenced here:

https://github.com/dependency-check/dependency-check-sonar-plugin/blob/e2efae6beb6f37c1a3d868143331f0d0d40a4177/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java#L55

**Comment by Reamer** [comment]
Thanks,
I will check that. Thanks for your hint.

**Comment by stevehipwell** [comment]
Hi, the plugin seems to be broken for us with both the JSON and XML reports.
> JSON-Analysis aborted
> XML-Analysis aborted due to: Mandatory elements are missing. Plugin is compatible to https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd

**Comment by stevehipwell** [comment]
@Reamer thanks for the prompt response! Do you have an estimation for when this will be released?

**Comment by Reamer** [comment]
It would be nice if you would build and test this plugin yourself and let me know if it works for you.
I am waiting with a release for next week and hope for an answer in #275.

**Comment by stevehipwell** [comment]
@Reamer do you have the ability to create RC release on this repo? Our SonarQube is deployed via automation and it'd be a quick test to update the version in the deploy config, otherwise I'll need to investigate manually deploying the jar or I'd need a test instance.

**Comment by Reamer** [comment]
Release done
SonarQube Marketplace: https://community.sonarsource.com/t/new-release-sonar-dependency-check-plugin-2-0-6/31228
