### ISSUE TITLE
"No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath" when HTML uploaded successfully 

### ISSUE THREAD

**Issue by bakedpatato** [dependency-check/dependency-check-sonar-plugin#275]
Hi,

I have a dependency-check report from a python3 project that I am trying to show in SQ via this plugin. 

When I run the sonar-scanner CLI on the python project I get 
"INFO: Upload Dependency-Check HTML-Report
 INFO: Process Dependency-Check report (done) | time=293ms" 
However, when I try to see the report I get "No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath".

I am running version 2.0.5 of the plugin and version  8.4.2  of SQ. 

Do you need any other information?

**Comment by Reamer** [comment]
Hi @bakedpatato,
I have tried to reproduce your problem, without success.

My Steps:
 - download sonarqube 8.4.2
 - install newest dependency-check-sonar-plugin version
 - start sonarqube
 - Run the following commands in `dependency-check-sonar-plugin/examples/multi-module-maven`
    - `mvn clean package dependency-check:aggregate`
    - `rm target/dependency-check-report.xml target/dependency-check-report.json`
    - `mvn sonar:sonar
 - Check Dependency-Check page in SonarQube

Can you reproduce your problem with the given steps?

**Comment by bakedpatato** [comment]
Hi, 

I apologize, I have a better reproduction case:

1. Run a dependency-check scan on a project off a branch 
2. Go to the dependency-check scan tab
The tab will show the error 

Then, when you run a scan on the master branch, the result from the master branch shows for all branches.

**Comment by Reamer** [comment]
For the branch function you need at least one developer license. I am not able to test this. Maybe your problem is also solved with #273.
