### ISSUE TITLE
sonar-dependency-check-2.0.6 crashes SonarQube 7.9.1

### ISSUE THREAD

**Issue by v7wolf** [dependency-check/dependency-check-sonar-plugin#280]
My SonarQube version is 7.9.1 (build 27448) Community Edition and I have updated sonar-dependency-check from version 2.0.5 to version 2.0.6. After a restart, SonarQube crashed and wouldn't start again.

Within the _web.log_ file there was the following error message:
_ERROR web[][o.s.s.p.Platform] Web server startup failed: Plugin Dependency-Check [dependencycheck] requires at least SonarQube 7.9.3.33150_
![image](https://user-images.githubusercontent.com/23187503/93983640-80b74f80-fd8b-11ea-8885-03700fcfc0cf.png)

I have observed other plugins which have updates. However, if the compatibility failed, the option to update was unavailable and the following message appeared while hovering over the new version: _Requires system update_
![image](https://user-images.githubusercontent.com/23187503/93984868-08518e00-fd8d-11ea-8011-8f6e0809856e.png)

The plugin was reverted manually to version 2.0.5 and SonarQube started without problems.
Could something like this be set in place, so that this problem can be avoided in the future?

**Comment by Reamer** [comment]
Hi @v7wolf,
the cause of your issue is:
This plugin is using [`7.9.3.33150`](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/pom.xml#L23) as a compile dependency. Therefore the plugin doesn't start with older sonarqube versions.
The update request https://github.com/SonarSource/sonar-update-center-properties/pull/149 has ` 7.9` the minimal version.

**Comment by v7wolf** [comment]
Hi @Reamer,
Thanks for the response!
I understood this from the error message.

I hope that others don't face this issue as well and would like to circumvent this. Is there any possibility that the marketplace understands this version requirement as well?
Because both 7.9.1 and 7.9.3 qualify for the 7.9 minimum version requirement. However, they are not the same.

**Comment by Reamer** [comment]
Hi @v7wolf.
@ganncamp was very fast with a quick fix. As mentioned in https://community.sonarsource.com/t/new-release-sonar-dependency-check-plugin-2-0-6/31228 sonarqube 7.9.1 isn't supported anymore and you should update to 7.9.4.
