### ISSUE TITLE
Integration with Security Hotspot not working in SonarQube

### ISSUE THREAD

**Issue by turbutran** [dependency-check/dependency-check-sonar-plugin#283]
Using SonarQube 8.4.2.36762

When opening a Security Hostpot for review error appears : "The request cannot be processed. Try again later."

**stacktrace :**
![image](https://user-images.githubusercontent.com/37378367/96274335-ac1b0c00-0fd0-11eb-8da3-22db137710ff.png)

**Possible cause :** 

Missing "textrange" node in /api/hotspots/show?hotspot response

![image](https://user-images.githubusercontent.com/37378367/96274886-53983e80-0fd1-11eb-9d4c-071480861414.png)

**Working hotspot response**
![image](https://user-images.githubusercontent.com/37378367/96274706-20ee4600-0fd1-11eb-91ee-879be0a15d97.png)

Many thanks for your help !

**Comment by Reamer** [comment]
@turbutran 
What type of project configuration (pom.xml, *.gradle, package-json.lock) do you use?

Do you make sure that these files are part of 'sonar.sources' because the issues are linked against these files?

With kind regards
Reamer

**Comment by turbutran** [comment]
@Reamer 

None of them, using 
- AzureDevops build task for DependencyCheck 
- alternatively CLI (.bat on windows)

Not 100% sure that was your question ?

Best regards, 
Bertrand

**Comment by Reamer** [comment]
AzureDevOps is working on a project (e.g. Maven project, Gradle project or a JavaScript project) Of course, there are several other project types, but this plugin supports the security hotspot function only for these three types.

**Comment by turbutran** [comment]
Does it mean i cant use security hotspot function with .net / msbuild projects (core 3.1 and 4.8 ?)

**Comment by Reamer** [comment]
No, .net / msbuild projects are not supported by this plugin with the security hotspot feature.

**Comment by turbutran** [comment]
Oh . Ok, 
too bad !
Any plan to support those projects ? any fork you know supporting them ?

Regards

**Comment by Reamer** [comment]
> Any plan to support those projects

Not from my side, because I have no experience with these projects.

> any fork you know supporting them

No. If someone programs this kind of feature, it would be nice to open a PR.
