### ISSUE TITLE
All vulnerabilities are assigned to CWE-937

### ISSUE THREAD

**Issue by JJ-Niemi** [dependency-check/dependency-check-sonar-plugin#285]
**Describe the bug**
All the vulnerabilities are listed as CWE-937 instead of the CWE the vulnerability is described in

**To Reproduce**
1. Start a sonarqube scan which imports the dependency-check result json file
2. Run the dependency-check generating the json file
3. End the sonarqube scan
4. Go to the sonarqube webui and look at the project detailed list over vulnerabilities
5. Take a look at the "Security Category/CWE

**Current behavior**
Only CWE-937 is listed with all the vulnerabilities 

**Expected behavior**
Each actual CWE should be listed as they are shown in the detail of the vulnerability.
This for the CWE-937 applies to the project it self, not the dependencies which are used in the project.
Also it had been nice to list those CVE that do not have a CWE in a CVE sub menu section too.

**Screenshots**
![image](https://user-images.githubusercontent.com/60340287/97161400-0c9f0b80-177e-11eb-8e55-091aac6c9115.png)

**Versions:**
-   dependency-check 6.0.2
-   sonarqube 8.3
-   dependency-check-sonar-plugin 2.0.6

**Additional context**
The CWE-937 applies to the project it self, not the dependencies which are used in the project.
Also it had been nice to list those CVE that do not have a CWE in a CVE sub menu section too.

**Comment by Reamer** [comment]
This plugin is using only [two rules](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/rule/KnownCveRuleDefinition.java#L55) (one with Security Hotspot function and one without). Currently SonarQube does not support overwriting or adding more cwes at runtime.
As far as I know the rules cannot be changed after startup and it is not possible to add suitable rules dynamically.
Please note that CWE-937 applies to all vulnerabilities as described in the [official documentation](https://cwe.mitre.org/data/definitions/937.html).

**Comment by haugsrud** [comment]
I have created an improvement on SonarSource for this issue. 

https://community.sonarsource.com/t/improved-breakdown-of-vulernabilities-ref-log4j-issue/54806

**Comment by haugsrud** [comment]
@Reamer according to SonarSource we should be able to assign any cwe-tags we'd like. Maybe this helps?

https://community.sonarsource.com/t/improved-breakdown-of-vulernabilities-ref-log4j-issue/54806/5?u=haugsrud

**Comment by Reamer** [comment]
> My understanding is that rule developers can assign whatever tags they’d like.

Yes, that is correct, but it is not possible to define rules dynamically at runtime. The rules must be defined at compile time.
