### ISSUE TITLE
Display Measures in Overview Tab + Create Issues

### ISSUE THREAD

**Issue by denizengin87** [dependency-check/dependency-check-sonar-plugin#290]
Hi,

I am not sure if this a bug report or a feature request:

When I export my dependency check results to SonarQube, I am able to see dependency-check-measures under Measures > Sidebar > OWASP-Dependency-Check and I am able to see the dependency-check-reports under More > Dependency-Check, as well. What I would expect else is that issues are created if something is found. I would also expect that the dependency-check-measures are shown in the overview tab, but the value for vulnerabilities remains zero though they exist in the report and measures. 
I am not sure whether I am doing something wrong or these are missing features. 

I use the newest Version of dependency-check-maven (6.0.3), sonar-maven-plugin (3.7.0.1746), dependency-check-sonar-plugin(2.0.6) and sonarqube (8.5.1.38104). 

Thx in advance!

**Comment by Reamer** [comment]
Hi @denizengin87 
which programming language has your project?
Can you give me the output of the Dependency Check plugin?
Something like
```
[INFO] ------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Linking 887 dependencies
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=804ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=806ms
```

**Comment by denizengin87** [comment]
Hi @Reamer,
yes, you are right. It is Java (Version 14 for this app).
Here is the output:
```
[INFO] ------------- Run sensors on module Personenportrait-Service - Hauptanwendung
[INFO] Load metrics repository
[INFO] Load metrics repository (done) | time=47ms
[INFO] Sensor JavaSquidSensor [java]
[INFO] Configured Java source version (sonar.java.source): 14
[INFO] JavaClasspath initialization
[INFO] JavaClasspath initialization (done) | time=9ms
[INFO] JavaTestClasspath initialization
[INFO] JavaTestClasspath initialization (done) | time=3ms
[INFO] Java Main Files AST scan
[INFO] 28 source files to be analyzed
[INFO] Load project repositories
[INFO] Load project repositories (done) | time=46ms
[INFO] 28/28 source files have been analyzed
[INFO] Java Main Files AST scan (done) | time=2076ms
[INFO] Java Test Files AST scan
[INFO] 7 source files to be analyzed
[WARNING] locking FileBasedConfig[/home/d.engin/.config/jgit/config] failed after 5 retries
[INFO] Java Test Files AST scan (done) | time=453ms
[INFO] 7/7 source files have been analyzed
[INFO] Java Generated Files AST scan
[INFO] 0 source files to be analyzed
[INFO] Java Generated Files AST scan (done) | time=1ms
[INFO] Sensor JavaSquidSensor [java] (done) | time=2586ms
[INFO] 0/0 source files have been analyzed
[INFO] Sensor CSS Rules [cssfamily]
[INFO] No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
[INFO] Sensor CSS Rules [cssfamily] (done) | time=1ms
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] No report imported, no coverage information will be imported by JaCoCo XML Report Importer
[INFO] Sensor JaCoCo XML Report Importer [jacoco] (done) | time=3ms
[INFO] Sensor C# Properties [csharp]
[INFO] Sensor C# Properties [csharp] (done) | time=1ms
[INFO] Sensor FindBugs Sensor [findbugs]
[INFO] Sensor FindBugs Sensor [findbugs] (done) | time=1ms
[INFO] Sensor SurefireSensor [java]
[INFO] parsing [/home/d.engin/Development/Projects/personenportraitservice/application/target/surefire-reports]
[INFO] Sensor SurefireSensor [java] (done) | time=108ms
[INFO] Sensor Removed properties sensor [java]
[WARNING] Property 'sonar.jacoco.reportPath' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin.
[WARNING] Property 'sonar.jacoco.itReportPath' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin.
[INFO] Sensor Removed properties sensor [java] (done) | time=1ms
[INFO] Sensor HTML [web]
[INFO] Sensor HTML [web] (done) | time=4ms
[INFO] Sensor XML Sensor [xml]
[INFO] 1 source files to be analyzed
[INFO] Sensor XML Sensor [xml] (done) | time=133ms
[INFO] 1/1 source files have been analyzed
[INFO] Sensor CheckstyleSensor [checkstyle]
[INFO] Checkstyle output report: /home/d.engin/Development/Projects/personenportraitservice/application/target/sonar/checkstyle-result.xml
[INFO] Checkstyle configuration: /home/d.engin/Development/Projects/personenportraitservice/application/target/sonar/checkstyle.xml
[INFO] Checkstyle charset: UTF-8
[INFO] Sensor CheckstyleSensor [checkstyle] (done) | time=340ms
[INFO] Sensor VB.NET Properties [vbnet]
[INFO] Sensor VB.NET Properties [vbnet] (done) | time=3ms
[INFO] ------------- Run sensors on module Personenportrait-Service - Frontend
[INFO] Sensor CSS Rules [cssfamily]
[INFO] No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
[INFO] Sensor CSS Rules [cssfamily] (done) | time=1ms
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] No report imported, no coverage information will be imported by JaCoCo XML Report Importer
[INFO] Sensor JaCoCo XML Report Importer [jacoco] (done) | time=1ms
[INFO] Sensor C# Properties [csharp]
[INFO] Sensor C# Properties [csharp] (done) | time=0ms
[INFO] Sensor HTML [web]
[INFO] Sensor HTML [web] (done) | time=0ms
[INFO] Sensor XML Sensor [xml]
[INFO] 1 source files to be analyzed
[INFO] Sensor XML Sensor [xml] (done) | time=10ms
[INFO] Sensor VB.NET Properties [vbnet]
[INFO] Sensor VB.NET Properties [vbnet] (done) | time=0ms
[INFO] ------------- Run sensors on module Personenportrait-Service - Parent
[INFO] 1/1 source files have been analyzed
[INFO] Sensor CSS Rules [cssfamily]
[INFO] No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
[INFO] Sensor CSS Rules [cssfamily] (done) | time=0ms
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] No report imported, no coverage information will be imported by JaCoCo XML Report Importer
[INFO] Sensor JaCoCo XML Report Importer [jacoco] (done) | time=2ms
[INFO] Sensor C# Properties [csharp]
[INFO] Sensor C# Properties [csharp] (done) | time=0ms
[INFO] Sensor HTML [web]
[INFO] Sensor HTML [web] (done) | time=0ms
[INFO] Sensor XML Sensor [xml]
[INFO] 1 source files to be analyzed
[INFO] Sensor XML Sensor [xml] (done) | time=25ms
[INFO] 1/1 source files have been analyzed
[INFO] Sensor VB.NET Properties [vbnet]
[INFO] Sensor VB.NET Properties [vbnet] (done) | time=0ms
[INFO] ------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Linking 138 dependencies
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=319ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=320ms
[INFO] Sensor Zero Coverage Sensor
[INFO] Sensor Zero Coverage Sensor (done) | time=16ms
[INFO] Sensor Java CPD Block Indexer
[INFO] Sensor Java CPD Block Indexer (done) | time=49ms
[INFO] SCM Publisher SCM provider for this project is: git
[INFO] SCM Publisher 1 source file to be analyzed
[INFO] SCM Publisher 0/1 source files have been analyzed (done) | time=79ms
[WARNING] Missing blame information for the following files:
[WARNING]   * pom.xml
[WARNING] This may lead to missing/broken features in SonarQube
[INFO] CPD Executor 11 files had no CPD blocks
[INFO] CPD Executor Calculating CPD for 17 files
[INFO] CPD Executor CPD calculation finished (done) | time=7ms
[INFO] Analysis report generated in 47ms, dir size=1 MB
[INFO] Analysis report compressed in 85ms, zip size=264 KB
[INFO] Analysis report uploaded in 1057ms
[INFO] ANALYSIS SUCCESSFUL, you can browse https://***/sonar/dashboard?id=de.thalia.ocp.personenportraitservice%3Apersonenportraitservice-parent
[INFO] Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[INFO] More about the report processing at https://***/sonar/api/ce/task?id=AXYDpl5bOKMQ2Uc_e173
[INFO] Analysis total time: 8.118 s
```
*** stands for the real server address of cause.

Thanks a lot

**Comment by Reamer** [comment]
The INFO output looks good. You can try a run with DEBUG (`mvn sonar:sonar -X`) to get more information. Maybe you see something useful.

You can also check this following links and check if your project is in the list. `****` should be replaced with your SonarQube server address.
You can also use the following links to check and see if your project is included in the list. `****` should be replaced with the address of your SonarQube server.
```
https://****/sonar/coding_rules?cwe=937&languages=neutral&open=OWASP%3AUsingComponentWithKnownVulnerability
```
or
```
https://****/sonar/coding_rules?cwe=937&languages=neutral&open=OWASP%3AUsingComponentWithKnownVulnerabilitySecurityHotspot
```

Can you reproduce the issues with one of our [example projects](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples)?

**Comment by denizengin87** [comment]
Hi @Reamer,
I can reproduce the issue with the example project. 

The first screenshot shows the measures:
![Measures](https://user-images.githubusercontent.com/43013656/100369092-be8f5900-3004-11eb-97ee-1d179154f227.png)
The second screenshot shows the depedency-check-report:
![report](https://user-images.githubusercontent.com/43013656/100369766-a10ebf00-3005-11eb-9ad7-06a78787a74d.png)
The third screenshot shows the overview with no vulnerabilities:
![overview](https://user-images.githubusercontent.com/43013656/100369827-b388f880-3005-11eb-877b-196f9a7982e9.png)
The fourth screenshot shows the issue overview with no issues:
![issues](https://user-images.githubusercontent.com/43013656/100369725-948a6680-3005-11eb-891e-d2093fd99513.png)
The debug output look good to me. I can post it as a file, if that helps?
When I open the two rules you posted, I can see that they only belong to quality profile neutral: 
![rule](https://user-images.githubusercontent.com/43013656/100377184-0fa54a00-3011-11eb-8053-a316bc972b3f.png)
The example project is associated to this profile for language neutral:
![profiles](https://user-images.githubusercontent.com/43013656/100377267-3794ad80-3011-11eb-9b95-97f470797bb4.png)
For java there is a custom quality profile assigned, which doesn't have these rules. Maybe this is the problem, but if it is, I can't copy the rules from neutral to the custom profile via neutral profile > bulk change > activate > choose custom profile. It tells me the change got ignored.

**Comment by Reamer** [comment]
I can't reproduce your issue.
![Multi-Module-Overview](https://user-images.githubusercontent.com/454320/100907619-d5352480-34ca-11eb-9cfc-77498decb4ac.png)

My environment:
 - SonarQube Community EditionVersion 8.5.1 (build 38104)
 - Dependency-Check 2.0.6
 - sonar-maven-plugin:3.6.1.1688 and sonar-maven-plugin:3.7.0.1746


> When I open the two rules you posted, I can see that they only belong to quality profile neutral:

It is correct that this two rules belong to the [`Neutral` quality profile](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/rule/NeutralProfile.java) and to the [`neutral` language ](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/rule/NeutralLanguage.java).
It is not possible to copy them into another language, as these rules are language-independent (neutral).

Have you seen your project in the rule view?
![rule_view](https://user-images.githubusercontent.com/454320/100905530-78386f00-34c8-11eb-818c-2e36eff4c23c.png)

Do you have other adjustments in your setup? Can you reproduce the problem with a local SonarQube setup where only the Dependencycheck plugin is additionally installed?

**Comment by patryksandomierski** [comment]
Hello,
We are facing similar issue. Report give us info that there are vulnerable dependencies but nothing shows up in Overview.
dep-check maven: 6.0.0 and 6.1.0
sonar: 8.4.2
dep-check sonar plugin: 2.0.7
sonar:sonar with -X flag example log:
`[DEBUG] 01:19:07.538 Get the best DependencyReason out of 1 for jackson-databind-2.10.4.jar
[DEBUG] 01:19:07.538 DependencyReasonWinner: pom.xml
[DEBUG] 01:19:07.539 We doesn't find a TextRange for jackson-databind-2.10.4.jar in pom.xml. We link to first line with LOW confidence`
at the end:
`[DEBUG] 01:19:07.607 Saving Metrics to Reasonfile DependencyCheckMetric [inputcomponent=pom.xml, totalDependencies=149, vulnerableDependencies=13, vulnerabilityCount=15, blockerIssuesCount=1, criticalIssuesCount=9, majorIssuesCount=4, minorIssuesCount=1, infoIssuesCount=0] 
02:19:07  [DEBUG] 01:19:07.608 Save measures on pom.xml`

**Comment by Reamer** [comment]
@patryksandomierski Are you able to reproduce this problem with a local SonarQube setup where only the Dependencycheck plugin is additionally installed?

**Comment by patryksandomierski** [comment]
@Reamer ill do it soon and let you know. Should I use same versions of software what we use in our infra?

**Comment by Reamer** [comment]
> Should I use same versions of software what we use in our infra?

Yes please

**Comment by patryksandomierski** [comment]
I setup the same version of software locally and results are identical.

**Comment by Reamer** [comment]
Are you able to reproduce this also with a [sample project](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples). If so, I need step-by-step instructions so I can reproduce this myself.

**Comment by yshzip** [comment]
For other users: do not forget generate not only html report, but and xml/json. And SQ will parse it .You can get OWASP measures.
