### ISSUE TITLE
Disabling dependency check sonar sensor when plugin does not active

### ISSUE THREAD

**Issue by tgrlbyrk** [dependency-check/dependency-check-sonar-plugin#291]
**Is your feature request related to a problem? Please describe.**
I want to run Dependency-Check for only a scheduled stage in pipeline, to achieve this I use maven profiles for only schedules. So I just put the plugins to this profile. It works fine. I see the reports on SonarQube. But even my build phase does not have dependency check and sonar dependency-check-sonar-plugin, it overwrites SonarQube security section to zero. "sonar.dependencyCheck.skip" does not help to achieve this, or I miss something.

**Describe the solution you'd like**
I do not want to update SonarQube security section for build phase(when there is no dependency check plugin in pom.xml). Is it possible to disable SonarQube sensor for plugin?

Here is the part of pipeline output:
(for mvn clean install sonar:sonar) 

```
...
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:/app/***-api/target/dependency-check-report.json
[INFO] JSON-Analysis skipped/aborted due to missing report file
[INFO] Using XML-Reportparser
[INFO] Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.xmlReportPath:/app/***-api/target/dependency-check-report.xml
[INFO] XML-Analysis skipped/aborted due to missing report file
[INFO] Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath:/app/***-api/target/dependency-check-report.html
[INFO] HTML-Dependency-Check report does not exist.
[INFO] Process Dependency-Check report (done) | time=9ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=10ms
...
```

**Comment by Reamer** [comment]
Hi @tgrlbyrk,
I assume that you run 'sonar:sonar' during your build. If you skip the `dependency-check-sonar-plugin` plugin with `sonar.dependencyCheck.skip` or your doesn't provide the reports, the dependency issues are not reported to SonarQube and SonarQube assumes that you have solved the issues.

If you don't want the ups and downs of security issues, you should always run a dependency-check before 'sonar:sonar'. I know that running dependency-check takes a long time if you are running with an empty vulnerability database, so I can recommend you to set up a central database -> [more information](https://jeremylong.github.io/DependencyCheck/data/database.html).

The property `sonar.dependencyCheck.skip` was introduced for projects which do not use the dependency-check plugin at all.
