### ISSUE TITLE
How to run dependency checker for .NET

### ISSUE THREAD

**Issue by nishaatr** [dependency-check/dependency-check-sonar-plugin#326]
**Describe the bug**
Is there any documentation on how to run dependency checker for .NET?
As I understand it, the Sonar plugin simply reads and uploads the dependency scanned results generated by some dependency checker tool. The closest doc I have come across is https://stackoverflow.com/questions/60571479/dependency-checker-with-teamcity-and-sonarqube-for-net-framework-and-net-core
It would beneficial to see some pointers here on how to run checker for .NET and Maven (and other langs). From the link above, I see a folder is passed to be scanned as opposed to SLN/.csproj. Is this the case or can we pass SLN/.csproj?
Also, some Sonar screenshots showing scanned dependency results would be good to see

**Comment by Reamer** [comment]
Take a look into this example project.

https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-project-csproj
