### ISSUE TITLE
Usage with SonarQube

### ISSUE THREAD

**Issue by AcidS76** [dependency-check/dependency-check-sonar-plugin#327]
Hi, I'm new with this plugin and with SonarQube and maybe this is not a issue but I need to understand the correct usage.
My configuration is:
sonar-maven-plugin (3.7.0.1746)
dependency-check-maven (6.0.3)
sonar-dependency-check (2.0.7)
sonarqube (8.6.0.39681)

I see the HTML report generated by OWASP dependency-check under the "more" tab but I don't see nothing (under the item "OWASP-Dependency-Check", all is 0 here) on the sidebar on the left inside "Measures" tab. Maybe am I doing anything wrong with configuration?
Thanks

**Comment by Reamer** [comment]
Please take a look into the README
https://github.com/dependency-check/dependency-check-sonar-plugin#using
