### ISSUE TITLE
Dependency check with Sonar 7.9.1 does not work

### ISSUE THREAD

**Issue by JosefFlyer** [dependency-check/dependency-check-sonar-plugin#349]
Hi!
My dependency check during the Sonarqube analysis does not work.

The output from the Sonarqube analysis log:
```INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Using JSON-Reportparser
WARN: JSON-Analysis aborted
INFO: Using XML-Reportparser
WARN: XML-Analysis aborted due to: Mandatory elements are missing. Plugin is compatible to https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd
INFO: Upload Dependency-Check HTML-Report
INFO: Process Dependency-Check report (done) | time=463ms
```

I am using the following libraries:
dependency-check-gradle: 6.0.5
Sonarqube: 7.9.1
sonar-dependency-check: 2.0.5

According to the following links, it should work with these versions:
https://github.com/dependency-check/dependency-check-sonar-plugin
https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/
https://docs.sonarqube.org/7.9/instance-administration/plugin-version-matrix/

It looks like that maybe the dependency-check.2.3.xsd is not compatible with the used one (version 2.5).

Unfortunately, I can not update the sonar-dependency-check plugin in Sonarqube to 2.0.7, because it says, that I have to do a major upgrade of Sonarqube at first.
See:
![Sonarqube_dependency_check_update](https://user-images.githubusercontent.com/78071676/105959327-0d488600-607c-11eb-898a-dcb08c62e9a7.JPG)
I also do not know, if a minor upgrade of Sonarqube to version 7.9.5 would solve this problem.

Do you have any suggestions about what I could do?
Is there a problem with the versions of the used libraries?

Thanks!

**Comment by Reamer** [comment]
Hi @JosefFlyer,
please update to at least the latest LTS version. Lower versions are not supported.
With the new SonarQube version you should be able to update to the latest plugin version.
If your problem is then still reproducible, please provide the DEBUG output.

**Comment by JosefFlyer** [comment]
Hi Reamer!
Thanks a lot! 
It is working now.
