### ISSUE TITLE
Dependency check does not work with Sonar 8.6

### ISSUE THREAD

**Issue by MehdiFi** [dependency-check/dependency-check-sonar-plugin#361]
Hi

My dependency check during Sonarqube analysis is not working due to incompatibility with RDS 8.6 version

Stacktrace of the errors: 
`{"task":
{"status":"FAILED",
"errorMessage":" Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: column oqp.organization_uuid does not exist\n  Position: 39\n### The error may exist in org.sonar.db.qualityprofile.QualityProfileMapper\n### The error may involve org.sonar.db.qualityprofile.QualityProfileMapper.selectByUuids-Inline
The error occurred while setting parameters\n### SQL: select           oqp.uuid as kee,     oqp.organization_uuid as organizationUuid,     oqp.parent_uuid as parentKee,     oqp.last_used as lastUsed,     oqp.user_updated_at as userUpdatedAt,     rp.uuid as rulesProfileUuid,     rp.name as name,     rp.language as language,     rp.rules_updated_at as rulesUpdatedAt,     rp.is_built_in as isBuiltIn         from org_qprofiles oqp     inner join rules_profiles rp on oqp.rules_profile_uuid = rp.uuid     where       oqp.uuid in  (  ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? )
Cause: org.postgresql.util.PSQ","hasScannerContext":true,"organization":"default-organization","branch":"dependency-check","branchType":"BRANCH","warningCount":0,"warnings":[]}}`

I am using the following libraries:
dependency-check-maven: 6.1.0
Sonarqube: 8.6
sonar-dependency-check: 2.0.7
![image](https://user-images.githubusercontent.com/78912127/107789227-a0a6da00-6d51-11eb-8aad-d6ebb827c88a.png)

I noticed that Dependency check works with RDS 8.5 snapshot (with same librairies versions: SQ: 8.6, DC: 2.0.7..)

Do you have any suggestions about what I could do ?

Thanks!

**Comment by Reamer** [comment]
This plugin does not interact directly with the SonarQube backend database. All communication is done via the SonarQube API.
Maybe it is a configuration error or a bug in your backend database (RDS) or in SonarQube.

**Comment by MehdiFi** [comment]
Configuration problem solved
