### ISSUE TITLE
Vulnerable dependency does not appear as Securiy Hotspot

### ISSUE THREAD

**Issue by MehdiFi** [dependency-check/dependency-check-sonar-plugin#379]
**Vulnerable dependency does not appear as Securiy Hotspot**

**Tool Versions:**

- SonarQube Version: 8.6.1
- dependency-check-maven: 6.1.0
- dependency-check-plugin: 2.0.7 

**The report is well generated.**

![image](https://user-images.githubusercontent.com/78912127/110445359-4e41aa80-80be-11eb-9eb7-1cf9184bf47c.png)

**Plugin configuration: The radio button is checked** 

![image](https://user-images.githubusercontent.com/78912127/110445043-04f15b00-80be-11eb-81d0-fe7a1667891a.png)

Many thanks for your help !

**Comment by Reamer** [comment]
Have any issues been reported to SonarQube?

**Comment by MehdiFi** [comment]
Thanks for your reactivity @Reamer . No issues have been reported to SonarQube

**Comment by Reamer** [comment]
This is the main problem. Please check the logs why no issues are reported.
You should see something like
```
[INFO] ------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Linking 138 dependencies
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=319ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=320ms
```

**Comment by MehdiFi** [comment]
Indeed, i have no linking dependencies appearing in log. But it appear on dependency-check report in SonarQube

------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:/build/target/dependency-check-report.json
[INFO] JSON-Analysis skipped/aborted due to missing report file
[INFO] Using XML-Reportparser
[INFO] Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.xmlReportPath:/build/target/dependency-check-report.xml
[INFO] XML-Analysis skipped/aborted due to missing report file
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=142ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=148ms
[INFO] Sensor Zero Coverage Sensor
[INFO] Sensor Zero Coverage Sensor (done) | time=8ms
[INFO] Sensor Java CPD Block Indexer
[INFO] Sensor Java CPD Block Indexer (done) | time=292ms
[INFO] SCM Publisher is disabled
[INFO] CPD Executor 54 files had no CPD blocks
[INFO] CPD Executor Calculating CPD for 42 files
[INFO] CPD Executor CPD calculation finished (done) | time=87ms
[INFO] Load New Code definition
[INFO] Load New Code definition (done) | time=48ms
[INFO] Analysis report generated in 357ms, dir size=3 MB
[INFO] Analysis report compressed in 695ms, zip size=653 KB
[INFO] Analysis report uploaded in 109ms

**Comment by Reamer** [comment]
The HTML report is completely detached from the other reports and is not used for the SonarQube issues. You also need the JSON or XML report. I recommend the JSON report.
Read the Readme file: https://github.com/dependency-check/dependency-check-sonar-plugin#plugin-configuration ;-)

**Comment by MehdiFi** [comment]
I am using Gitlab CI/CD. 
I have configured the dependency-check json report via SonarQube
![image](https://user-images.githubusercontent.com/78912127/110498034-40f4e200-80f7-11eb-897a-b7d6d9316537.png)

I have added also atifacts to browse to target folder, as you cann see, i have only the html report
![image](https://user-images.githubusercontent.com/78912127/110498574-be205700-80f7-11eb-8656-fc3f7b88bf6c.png)

**Comment by Reamer** [comment]
I cannot give support for GitLab CI. Please take a look at the GitLab CI dependency checking documentation to enable JSON or XML reporting.
