### ISSUE TITLE
Security Hotspots report not mention the same priority review Levels after importing issues from OWASP dependency check

### ISSUE THREAD

**Issue by MehdiFi** [dependency-check/dependency-check-sonar-plugin#382]
**Security Hotspots report not mention the same priority review after importing issues from OWASP dependency check**

**Tools:** 
- Dependency-check plugin: 2.0.7
- Dependency-check-mave: 6.1.2
- SonarQube: 8.6.1

**Html et Json report are used** 

`[INFO] ------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Linking 1 dependencies
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=274ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=274ms
[INFO] Sensor Zero Coverage Sensor
[INFO] Sensor Zero Coverage Sensor (done) | time=0ms
[INFO] SCM Publisher SCM provider for this project is: git
[INFO] SCM Publisher 1 source file to be analyzed
[INFO] SCM Publisher 1/1 source file have been analyzed (done) | time=87ms
[INFO] CPD Executor Calculating CPD for 0 files
[INFO] CPD Executor CPD calculation finished (done) | time=0ms
[INFO] Load New Code definition
[INFO] Load New Code definition (done) | time=19ms
[INFO] Analysis report generated in 99ms, dir size=315 KB
[INFO] Analysis report compressed in 18ms, zip size=69 KB
[INFO] Analysis report uploaded in 45ms`

**Vulnerable dependency have a hight severity** 

![image](https://user-images.githubusercontent.com/78912127/110920155-58151900-831d-11eb-9722-2e0f35f46027.png)
![image](https://user-images.githubusercontent.com/78912127/110920199-65320800-831d-11eb-8d1c-58ea6f8cd0d5.png)

**But Security Hotspot mention a low priority of review**
![image](https://user-images.githubusercontent.com/78912127/110920418-a7f3e000-831d-11eb-923b-03cb4aa57979.png)

Thanks for help

**Comment by Reamer** [comment]
That is correct and cannot be changed.
Have a look at https://community.sonarsource.com/t/styling-security-hotspot-rules/29452/3.
