### ISSUE TITLE
Make plugin available via marketplace

### ISSUE THREAD

**Issue by ghenadiibatalski** [dependency-check/dependency-check-sonar-plugin#388]
Hello,

is it possible to provide the plugin via the marketplace? Sometimes, updates require to purge the plugins folder. Which is not really bad, if the plugins were installed via the marketplace. But manually installed plugins need to be reinstalled every time.

I don't know, if there are some pitfalls or additional maintenance overhead of a marketplace integration, but the option could be interesting.

Than you and kind regards,

Gena

**Comment by Reamer** [comment]
This plugin is already part of the SonarQube marketplace.
Configuration file for the marketplace: https://github.com/SonarSource/sonar-update-center-properties/blob/master/dependencycheck.properties
