### ISSUE TITLE
Reports not found in "Run Code Analysis" AzureDevOps

### ISSUE THREAD

**Issue by iamrahul127** [dependency-check/dependency-check-sonar-plugin#409]
We are using dependency check sonar qube plugin with SonarQube Community Edition Version 8.7.1 integrated with AzureDeops Server 2020. 

Dependency Check Task writes report into  & Log as below.

 Starting: Dependency Check
 Task         : OWASP Dependency Check
 Description  : Dependency Check is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project's dependencies.
 Version      : 6.0.2
 Author       : Dependency Check
 Help         : [More Information](https://jeremylong.github.io/DependencyCheck/index.html)

 Starting Dependency Check...
 **Setting report directory to F:\A\BUILDM02-01\_work\2\TestResults\dependency-check
 Creating report directory at F:\A\BUILDM02-01\_work\2\TestResults\dependency-check**
 Downloading Dependency Check latest installer from GitHub..
 Dependency Check script set to F:\A\BUILDM02-01\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.0.2\dependency-check\bin\dependency-check.bat
 Invoking Dependency Check...
 Path: F:\A\BUILDM02-01\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.0.2\dependency-check\bin\dependency-check.bat
 Arguments: --project "WE.Education.CDN" --scan "F:\A\BUILDM02-01\_work\2\s" --out "F:\A\BUILDM02-01\_work\2\TestResults\dependency-check" --format ALL
 [command]C:\windows\system32\cmd.exe /D /S /C "F:\A\BUILDM02-01\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.0.2\dependency-check\bin\dependency-check.bat --version"
 Dependency-Check Core version 6.1.5
 
 [command]C:\windows\system32\cmd.exe /D /S /C "F:\A\BUILDM02-01\_work\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.0.2\dependency-check\bin\dependency-check.bat --project WE.Education.CDN --scan F:\A\BUILDM02-01\_work\2\s --out F:\A\BUILDM02-01\_work\2\TestResults\dependency-check --format ALL"
 [INFO] Checking for updates
 [INFO] Skipping NVD check since last check was within 4 hours.
 [INFO] Skipping RetireJS update since last update was within 24 hours.
 [INFO] Check for updates complete (234 ms)
 [INFO]
====Log Removed & Continued====
[INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-report.xml
 [INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-report.html
 [INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-report.json
 [INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-report.csv
 [INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-report.sarif
 [INFO] Writing report to: F:\A\BUILDM02-01\_work\2\TestResults\dependency-check\dependency-check-junit.xml

SonarQube configurations are as below.
${Agent.BuildDirectory}/TestResults/dependency-check/dependency-check-report.html
${Agent.BuildDirectory}/TestResults/dependency-check/dependency-check-report.json
${Agent.BuildDirectory}/TestResults/dependency-check/dependency-check-report.xml

Run Code Analysis Task logs clearly shows that it's trying to search logs in wrong directory which is F:\A\BUILDM02-01\_work\2\**s\${Agent.BuildDirectory}\**TestResults\dependency-check\dependency-check-report.json

Logs as below.

Starting: Run Code Analysis

Task         : Run Code Analysis
Description  : Run scanner and upload the results to the SonarQube server.
Version      : 4.18.0
Author       : sonarsource
Help         : Version: 4.18.0. This task is not needed for Maven and Gradle projects since the scanner should be run as part of the build.

[More Information](http://redirect.sonarsource.com/doc/install-configure-scanner-tfs-ts.html)

[command]F:\A\BUILDM02-01\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.18.0\classic-sonar-scanner-msbuild\SonarScanner.MSBuild.exe end
SonarScanner for MSBuild 5.1
Using the .NET Framework version of the Scanner for MSBuild
Post-processing started.
Calling the TFS Processor executable...
Attempting to locate the CodeCoverage.exe tool...
Attempting to locate the CodeCoverage.exe tool using setup configuration...
Code coverage command line tool: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe
Fetching code coverage report information from TFS...
Attempting to locate a test results (.trx) file...
Looking for TRX files in: F:\A\BUILDM02-01\_work\2\TestResults
No test results files found
Did not find any binary coverage files in the expected location.
Falling back on locating coverage files in the agent temp directory.
Searching for coverage files in F:\A\BUILDM02-01\_work\_temp
No coverage files found in the agent temp directory.
Coverage report conversion completed successfully.
The TFS Processor has finished
Calling the SonarScanner CLI...
INFO: Scanner configuration file: F:\A\BUILDM02-01\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.18.0\classic-sonar-scanner-msbuild\sonar-scanner-4.4.0.2170\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: F:\A\BUILDM02-01\_work\2\.sonarqube\out\sonar-project.properties
INFO: SonarScanner 4.4.0.2170
INFO: Java 1.8.0_211 Oracle Corporation (64-bit)
INFO: Windows Server 2016 10.0 amd64
INFO: User cache: C:\Users\azureuser\.sonar\cache
INFO: Scanner configuration file: F:\A\BUILDM02-01\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.18.0\classic-sonar-scanner-msbuild\sonar-scanner-4.4.0.2170\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: F:\A\BUILDM02-01\_work\2\.sonarqube\out\sonar-project.properties
INFO: Analyzing on SonarQube server 8.7.1
INFO: Default locale: "en_US", source code encoding: "windows-1252" (analysis is platform dependent)
WARN: SonarScanner will require Java 11 to run starting in SonarQube 9.x
=======Logs Removed =====
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Using JSON-Reportparser
INFO: Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:F:\A\BUILDM02-01\_work\2\s\${Agent.BuildDirectory}\TestResults\dependency-check\dependency-check-report.json
INFO: JSON-Analysis skipped/aborted due to missing report file
INFO: Using XML-Reportparser
INFO: Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.xmlReportPath:F:\A\BUILDM02-01\_work\2\s\${Agent.BuildDirectory}\TestResults\dependency-check\dependency-check-report.xml
INFO: XML-Analysis skipped/aborted due to missing report file
INFO: Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath:F:\A\BUILDM02-01\_work\2\s\${Agent.BuildDirectory}\TestResults\dependency-check\dependency-check-report.html
INFO: HTML-Dependency-Check report does not exist.
INFO: Process Dependency-Check report (done) | time=0ms
INFO: Sensor Dependency-Check [dependencycheck] (done) | time=0ms
INFO: Sensor C# [csharp]
INFO: Importing results from 5 proto files in 'F:\A\BUILDM02-01\_work\2\.sonarqube\out\0\output-cs'
INFO: Importing 1 Roslyn report
INFO: Sensor C# [csharp] (done) | time=125ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=47ms
INFO: SCM Publisher SCM provider for this project is: git
INFO: SCM Publisher 1 source file to be analyzed
INFO: SCM Publisher 0/1 source files have been analyzed (done) | time=141ms
WARN: This may lead to missing/broken features in SonarQube
INFO: CPD Executor 5 files had no CPD blocks
INFO: CPD Executor Calculating CPD for 44 files
INFO: CPD Executor CPD calculation finished (done) | time=78ms
INFO: Analysis report generated in 235ms, dir size=5 MB
INFO: Analysis report compressed in 828ms, zip size=1 MB
INFO: Analysis report uploaded in 234ms
INFO: ANALYSIS SUCCESSFUL, 
====== Removed=======
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 41.248s
INFO: Final Memory: 18M/443M
INFO: ------------------------------------------------------------------------
The SonarScanner CLI has finished
16:28:52.615  Post-processing succeeded.
##[section]Finishing: Run Code Analysis

**Versions :**

-   dependency-check : 6
-   sonarqube : Community Edition Version 8.7.1
-   dependency-check-sonar-plugin: 2.0.7
-   Asuze DevOps server 2020

**Additional context**
I can clearly see that dependency-check is writing report in F:\A\BUILDM02-01\_work\2\TestResults\dependency-check by default without specifying any "Report Path" and "Run Code Analysis" check for report at F:\A\BUILDM02-01\_work\2\s\${Agent.BuildDirectory}\TestResults\dependency-check. But question is how do I fixed it?

**Comment by iamrahul127** [comment]
I will definitely improve formatting next time. Thank you for helping with markdown help.

I looked into the code file `JsonReportFile.java` and think that following line is responsible for evaluating the correct path based on value passed to it. In my case value of _path_ parameter below is `${Agent.BuildDirectory}\TestResults\dependency-check `which I have set in **SonarQube**.

`File report = pathResolver.relativeFile(fileSystem.baseDir(), path);`

I am not sure how to I make sure `${Agent.BuildDirectory}` is evaluated correctly. BTW I managed to solve problem by setting report path to `..\TestResults\dependency-check\dependency-check-report.json`. So. no more using environment variable.

**Comment by Reamer** [comment]
As mentioned, your environment variable `${Agent.BuildDirectory}` is not resolved within SonarScanner (Java). Therefore, you should change your configuration in SonarQube, as this configuration value is used when the SonarScanner is already running.

Unfortunately, I don't know AzureDevOps, so I can only give an Maven example.
```
mvn sonar:sonar -Dsonar.dependencyCheck.jsonReportPath=${myenvvariable}/dependency-check/dependency-check-report.json
```

I am closing this issue because your problem is solved.
