### ISSUE TITLE
dependency check + SonarQube + Composer: No project configuration file

### ISSUE THREAD

**Issue by vladkras** [dependency-check/dependency-check-sonar-plugin#479]
I'm successfully using experimental feature of dependency check and all found vulnerabilities are transferred to SonarQube Security Hotspots, but they are not linked to anything. Maybe this is the problem:

```
INFO: No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.
```

As I see in your code, it's not looking for default [composer.lock](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control) file.

It is possible to add Composer lock file support too? I beleive, it has almost the same structure as npm's package-lock.json

**Comment by Reamer** [comment]
You should be right.
Please create a PR with a simple example composer project in the [examples](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) folder with some vulnerabilities. With this I should be able to create the dependency-check reports and develop the feature.

**Comment by mieliespoor** [comment]
Although I don't have an example project, I'm seeing the same for a .net framework (4.x) project where the xml file is being used.

```
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Using JSON-Reportparser
INFO: Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:C:\ba\xml-data\build-dir\CATR-VQ-JOB1\_tst\dependency-check-report.json
INFO: JSON-Analysis skipped/aborted due to missing report file
INFO: Using XML-Reportparser
INFO: No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.
INFO: Linking 59 dependencies
INFO: Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath:C:\ba\xml-data\build-dir\CATR-VQ-JOB1\_tst\dependency-check-report.html
INFO: HTML-Dependency-Check report does not exist.
INFO: Process Dependency-Check report (done) | time=276ms
INFO: Sensor Dependency-Check [dependencycheck] (done) | time=276ms
```

**Comment by vladkras** [comment]
Example is almost ready, I'll push it ASAP

**Comment by mieliespoor** [comment]
still an issue

**Comment by vladkras** [comment]
I don't have enough time right now to finish this file
