### ISSUE TITLE
Dependency check : chrome trace event : setting min ver to reduce vulnerability count

### ISSUE THREAD

**Issue by raghuraman-ace** [dependency-check/dependency-check-sonar-plugin#495]
Hi,

We are using dependency check plugin in sonarqube. There are 2000 + vulnerabilities are shown in chrome-trace-event. I understand that the tool is saying all possible vulnerabilities exists in the package applicable for each chrome version, starting from 1.0 to 92.x.

But my question is, we are using latest version of chrome and we would educate all our customers about the same. 
would it be possible to set a rule in Sonar that it understands the minimum chrome version that is set is 70.5 per se.  so that it should show only applicable vulnerabilities. It should not show all vulnerabilities that are applicable to chrome ver < 70.5.
 Your help is much appreciated.

Regards
Raghu CR

**Comment by Reamer** [comment]
Hi @raghuraman-ace,
Please have a look at the README. https://github.com/dependency-check/dependency-check-sonar-plugin#note
This plugin doesn't generate the report. Please adjust the report with [DependencyCheck](https://github.com/jeremylong/DependencyCheck).
For example you can use a suppression file.
