### ISSUE TITLE
What determines the review priority in Security Hotspots?

### ISSUE THREAD

**Issue by luisxiaomai** [dependency-check/dependency-check-sonar-plugin#502]
Hi there,

Currently I see all the dependency vulnerabilities marked review priority as **LOW** level, what determines the review priority in Security Hotspots? Can the review priority be **HIGH** or **MEDIUM** based on the dependency vulnerability score/Severity?

<img width="1353" alt="Screen Shot 2021-09-08 at 2 42 54 PM" src="https://user-images.githubusercontent.com/6835229/132459511-e24daa2c-7b4f-488f-9ddc-fb4abc877e7d.png">

**Comment by Reamer** [comment]
HI @luisxiaomai 
you can find more information in #272 and in the sonar [community thread #29452](https://community.sonarsource.com/t/styling-security-hotspot-rules/29452)
At the moment it should not be possible to increase the priority.
