### ISSUE TITLE
Example or guideline for Java and .Net projects

### ISSUE THREAD

**Issue by tgnanakumar** [dependency-check/dependency-check-sonar-plugin#519]
I couldn't find a clear example or guideline for running dependency check for Java (based on Maven) and .Net projects with GitHub Actions workflow, and pushing the results to SonarQube.

Any pointers or help appreciated.

**Comment by Reamer** [comment]
>  Java (based on Maven)

Take a look at [single-module-maven](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/single-module-maven) or [multi-module-maven](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-module-maven)

> and .Net projects

Take a look at [multi-project-csproj](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-project-csproj)

> GitHub Actions workflow

You can use normal shell commands as in [this project](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/34e283aa74976e7d0bf9addc4ec8264c672d1c12/.github/workflows/testing.yml#L28).

> pushing the results to SonarQube

Adjust your settings as in this [this project](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/34e283aa74976e7d0bf9addc4ec8264c672d1c12/pom.xml#L22-L25) and run a normal shell command.
