### ISSUE TITLE
Issue from dependency-check display on "issue of sonarqube"

### ISSUE THREAD

**Issue by Dubouchj** [dependency-check/dependency-check-sonar-plugin#528]
Is it possible to see issues/vulnerabilities from dependency-check report on the issue of the SonarQube project (/project/issues?id=test&resolved=false)?

I did some tests with this [project](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples/multi-project-csproj) which display 3 vulnerabilities but It is not displayed on the "Issues".

![image](https://user-images.githubusercontent.com/33114629/137078889-23953e9c-0c95-4340-a3fe-b30deadc64be.png)
![image](https://user-images.githubusercontent.com/33114629/137078914-17ea5dd2-30df-4467-be3a-478a21aece36.png)

**Comment by Reamer** [comment]
Please attach the log output of this plugin while running Sonar Maven.

**Comment by Reamer** [comment]
No response
