### ISSUE TITLE
build.gradle file not found as project configuration file

### ISSUE THREAD

**Issue by brennon** [dependency-check/dependency-check-sonar-plugin#548]
**Describe the bug**
I have the plugin successfully uploading reports to SonarQube from Jenkins builds. However, all builds show this in the log:

```
No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.
```

My multi-module Gradle project has a `build.gradle` file in root folder. It seems like it should be included in the plugin's default glob pattern for configuration files, but per [this example](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/2312bc8b3b6c91833d7982ce5de567bd37393101/examples/single-module-gradle/build.gradle#L39), that file includes the following:

```
sonarqube {
	properties {
		properties["sonar.sources"] += "build.gradle"
	}
}
```

**Current behavior**
Logs include the line shown above. Findings are not linked in the SonarQube project.

**Expected behavior**
Findings are linked in the SonarQube project.

**Versions (please complete the following information):**

-   dependency-check: 6.2.2
-   sonarqube: 8.7
-   dependency-check-sonar-plugin: 2.0.8

**Comment by Reamer** [comment]
Can you check the debug log and look for [this log line](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReasonSearcher.java#L70).
Can you get the Example project up and running?

**Comment by haroldlbrown** [comment]
I am encountering the same problem in a Gradle multi-module project.

I have added 

```groovy
sonarqube {
    properties {
        // ...
        properties["sonar.sources"] += "$rootDir.path/build.gradle"
    }
}
```
but I get
 
```text
Sensor Dependency-Check [dependencycheck]
Process Dependency-Check report
Using JSON-Reportparser
No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.
Linking 190 dependencies
```

Is there an example for getting dependency-check-sonar-plugin to work with a Gradle multi-module project?
