### ISSUE TITLE
 Dependency-check-sonar-plugin 2.0.8 Issue for Sonarqube 8.9 version

### ISSUE THREAD

**Issue by ajena280495** [dependency-check/dependency-check-sonar-plugin#566]
Sonarqube Version- 8.9
Dependency Check Plugin -2.0.8
Web server as reverse proxy- IIS 10 version
OS- Windows server 2019

Problem i faced this for all project which was analysed.

I installed the plugin via sonarqube market place.After installing i faced issue after project analysis the measure tab for each project it was missing . As i am using IIS reverse proxy i have checked that if i am working on localhost:9000 its working fine but on remote browser something is blocking to get the response. Using Dev-tools i have inspected that i am getting 400 error for measure tab page.I have tried to disable my antivirus,firewall but didnt worked.Following some tips on sonarqube community i have increased my URL Length and query lenght but it didnt worked for me. So i just uninstalled all the plugins>deleted the data/es7  directory> and restarted the sonarqube server.

 Everything came back to life the measure tab was working fine on remote browser. I am attaching the screenshots for your reference. Please guide us to solve this problem and use dependency check sonar plugin.If it is a bug the please fix it. Thank you.

**Comment by Reamer** [comment]
If it works directly without an IIS reverse proxy, you need to look at the configuration of your reverse proxy.
I would look at things like the maximum response size.
Look at the access log from the SonarQube server and the proxy server.
I do not know the IIS web server and cannot help with the configuration here.

**Comment by ajena280495** [comment]
My config for IIS reverse proxy given below.

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <directoryBrowse enabled="false" />
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" enabled="true" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:9000/{R:1}" />
                </rule>
				
				<rule name="HTTPS rewrite behind ELB rule" stopProcessing="true">
<match url="^(.*)$" ignoreCase="false" />
<conditions>
<add input="{HTTP_X_FORWARDED_PROTO}" pattern="^http$" ignoreCase="false" />
</conditions>
<action type="Redirect" redirectType="Found" url="https://{SERVER_NAME}{URL}" />
</rule>
            </rules>
         
        </rewrite>
        <security>
            <requestFiltering allowDoubleEscaping="false" allowHighBitCharacters="true">
                <requestLimits maxUrl="4096" maxQueryString="3000" />
                <fileExtensions allowUnlisted="true" />
                <verbs allowUnlisted="true" />
            </requestFiltering>
        </security>
    </system.webServer>
</configuration>
