### ISSUE TITLE
Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API

### ISSUE THREAD

**Issue by Heman4022** [dependency-check/dependency-check-sonar-plugin#630]
**Describe the bug**
Hi All,
Not sure if this is the right thread or channel to report this error.
i’m using latest version 9.3 SonarQube , Scanner is 2.13.1 and dependency check is 3.0. Suddenly the jenkins failed to pass the dependency check and below is the logs. Appreciate if anyone can help to tell the solution, thanks in advance.

[ERROR] NodeAuditAnalyzer failed on /var/lib/jenkins/workspace/ZGQ-DEPLOY-GOLD-WEB/package-lock.json
[WARN] An error occurred while analyzing '/var/lib/jenkins/workspace/XXX-DEPLOY-WEB/package-lock.json' (Node Audit Analyzer).
[INFO] Finished Node Audit Analyzer (1 seconds)
[INFO] Finished RetireJS Analyzer (1 seconds)
[WARN] Unable to determine Package-URL identifiers for 411 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (7 seconds)
[INFO] Writing report to: /var/lib/jenkins/workspace/XXX-DEPLOY-WEB/.dependency-check/dependency-check-report.json
[INFO] Writing report to: /var/lib/jenkins/workspace/XXX-DEPLOY-WEB/.dependency-check/dependency-check-report.html
[ERROR] Could not perform Node Audit analysis. Invalid payload submitted to Node Audit API.
Build step 'Execute shell' marked build as failure

**Comment by Reamer** [comment]
This error does not come from this plugin, but from [dependency-check](https://github.com/jeremylong/DependencyCheck).
