### ISSUE TITLE
Historical Reports

### ISSUE THREAD

**Issue by ryan-fortin** [dependency-check/dependency-check-sonar-plugin#643]
Our organization is running sonarqube 9.3.0 with dependency-check 7.0.0 and dependency-check-sonar-plugin 3.0.0 in our CI pipeline to generate nightly reports.  Is there a way to view reports from the previous nights run?  

For example, if we analyze our main brain daily it seems previous days dependency check reports are lost in sonarqube.  Under the 'More' dropdown in sonarqube the dependency check report only shows for the last run.

**Comment by Reamer** [comment]
The current implementation of the report in the SonarQube GUI is more of a hack than a clean implementation. Currently I am not aware of any way to implement this.
