### ISSUE TITLE
Dependency check results/reports lost after updating to the latest SonarQube docker image

### ISSUE THREAD

**Issue by brileyd** [dependency-check/dependency-check-sonar-plugin#653]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is expected functionality with using the docker image, or if this is a problem.  I updated to the latest docker image and all the dependency check results are gone.  My suspicion is the results must be stored internally to the container and when updated they are lost.

**Describe the solution you'd like**
I would like the result to be stored to a docker volume that could be linked to the container.

**Describe alternatives you've considered**
If the results are stored in the internal elasticsearch instance, possibly allow for running a separate container.

**Additional context**
In the image, you can see that there is no report.
![sq1](https://user-images.githubusercontent.com/22780214/168862246-5fe0c87b-ab43-4ff4-bfe4-5997c75b48b1.png)

In the second image, before the update, we have 972 vulnerabilities.
![sq2](https://user-images.githubusercontent.com/22780214/168862260-bc38fdd0-291b-47b5-9ca2-d02d03e56659.png)

In the third image, after the update, we have 1 vulnerability.
![sq3](https://user-images.githubusercontent.com/22780214/168862280-311658c8-3f8a-4b77-8860-149fe5d2ee67.png)

If more information is needed, please let me know.

**Comment by Reamer** [comment]
Please provide the log output of this plugin during sonar execution.

**Comment by brileyd** [comment]
After reviewing the logs, I found that I had made a typo in the path of the 3 volumes in my docker-compose file, which caused everything to be stored in the container.  I fixed the typos, copied the directories to the host and ran the upgrade again without losing information.

This was **not** an issue with the plugin, but was an error on my part.  Sorry for wasting your time.

Thank you!
