### ISSUE TITLE
Is dependency-check-sonar-plugin compatible with Sonarqube EE 9.4?

### ISSUE THREAD

**Issue by shafemoh** [dependency-check/dependency-check-sonar-plugin#666]
Hi team,
we are currently hosting **Sonarqube EE 9.2.4** and we will be **upgrading to Sonarqube 9.4.0**. We are currently using [sonar-dependency-check-plugin-2.0.8.jar](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar).
Should we upgrade the Dependency check plugin to some higher version (if so, to which version ? )
OR Can we stay on [sonar-dependency-check-plugin-2.0.8.jar](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar) ?

Regards @shafemoh

**Comment by Reamer** [comment]
Only the latest version is supported by this project. If you have problems with this plugin, I am not willing to help you.
