### ISSUE TITLE
Support OWASP 2021 categories in SQ 9.4ff

### ISSUE THREAD

**Issue by Janpopan** [dependency-check/dependency-check-sonar-plugin#695]
**Is your feature request related to a problem? Please describe.**
From SQ 9.4 OWASP 2021 categories are supported to

**Describe the solution you'd like**
Please add support for this categories

**Comment by Reamer** [comment]
I added the feature to branch [owasp_2021](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/owasp_2021). 
Unfortunately, the category does not yet exist in the current LTS version, so the change cannot yet be included in the master branch. However, you can compile and include the plugin yourself.

**Comment by Reamer** [comment]
Added to master branch.
