### ISSUE TITLE
HTML error when switching with another plugin

### ISSUE THREAD

**Issue by guillain** [dependency-check/dependency-check-sonar-plugin#704]
**Describe the bug**
_The request cannot be processed. Try again later._
This error message appears when we navigate from another plugin window to this one.

**To Reproduce**
It's mandatory to have  another plugin installed to do the switch between the both.
After installation (of the 2 plugins), it's really easy to reproduce the behaviour:
1. Select the other plugin
2. Select Dependency-check plugin

**Current behavior**
Error message in the web page

**Expected behavior**
At least the blank page of the dependency-check plugin

**Screenshots**
The request cannot be processed. Try again later.

**Versions (please complete the following information):**

-   dependency-check: 7.1.0
-   sonarqube:  8.9.9
-   dependency-check-sonar-plugin: 2.0.8, 3.0.0, 3.0.1

**Additional context**

**Comment by Reamer** [comment]
Where do you switch between plugins?
In the admin interface or in the project interface.

**Comment by Guillain-A** [comment]
In the project interface, tks!

**Comment by Reamer** [comment]
I have only this one plugin installed, so I can't reproduce the problem.

> The request cannot be processed. Try again later.

Is no error message of this plugin, does the SonarQube server show more information?

**Comment by Guillain-A** [comment]
Nope, nothing was found :/
