### ISSUE TITLE
Unable to see Vulnerabilities reported by dependency-check

### ISSUE THREAD

**Issue by kunal-deshmukh-deltatre** [dependency-check/dependency-check-sonar-plugin#710]
We have installed the Enterprise Sonarqube server on-prem and pushing project analysis and dependency-check results to this server. But Sonarqube Server is not able to display vulnerabilities that are found by dependency-check. Though we are able to see HTML reports on sonar.
This is happening for any kind of project (MSBuild, Typescript, or Java).

But If I spin up the local Sonarqube server and do the analysis locally with[ dependency-check ](https://github.com/jeremylong/DependencyCheck)it works perfectly fine as expected.

We have also installed Dependency-Check Plugin on the SonarQube server.

SonarQube Version : Version 9.6.1
dependency-check: version 7.2.1

Let me know if you need more information. We are kind of stuck and unable to understand why it is not working on Hosted SonarQube Server

**Comment by Reamer** [comment]
What does the sonar scanner output during analysis? I'm interested in the following block.

Example log output.
```
[INFO] ------------- Run sensors on project
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Using JSON-Reportparser
[INFO] Linking 14 dependencies
[INFO] Upload Dependency-Check HTML-Report
[INFO] Process Dependency-Check report (done) | time=404ms
[INFO] Sensor Dependency-Check [dependencycheck] (done) | time=404ms
```

Which plugin version do you use?

**Comment by kunal-deshmukh-deltatre** [comment]
Hi @Reamer 
Here is the output.
Plugin Version: 3.0.1

Do you think it has something to do with SonarQube Server?

Output 1
```
INFO: Sensor Analysis Warnings import [csharp]
INFO: Sensor Analysis Warnings import [csharp] (done) | time=1ms
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Using JSON-Reportparser
INFO: Linking 1012 dependencies
INFO: Upload Dependency-Check HTML-Report
INFO: Process Dependency-Check report (done) | time=1103ms
INFO: Sensor Dependency-Check [dependencycheck] (done) | time=1103ms
```
Output 2: 
```
INFO: Sensor C# [csharp] (done) | time=594ms
INFO: Sensor Analysis Warnings import [csharp]
INFO: Sensor Analysis Warnings import [csharp] (done) | time=0ms
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Using JSON-Reportparser
INFO: No project configuration file, e.g. pom.xml, *.gradle, *.gradle.kts, package-lock.json found, therefore it isn't possible to correctly link dependencies with files.
INFO: Linking 8 dependencies
INFO: Upload Dependency-Check HTML-Report
INFO: Process Dependency-Check report (done) | time=828ms
INFO: Sensor Dependency-Check [dependencycheck] (done) | time=828ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=31ms
```

**Comment by Reamer** [comment]
Output looks good.

> Do you think it has something to do with SonarQube Server?

The circumstantial evidence points to this. But I probably can't help you with that.

**Comment by garry-t** [comment]
same for me for Developer version of SonarQube

**Comment by garry-t** [comment]
same for me for Developer version of SonarQube
```12:55:08.318 DEBUG: Saving Metrics to project DependencyCheckMetric [inputcomponent=[key=project], totalDependencies=41337, vulnerableDependencies=21, vulnerabilityCount=48, blockerIssuesCount=1, criticalIssuesCount=29, majorIssuesCount=16, minorIssuesCount=2, infoIssuesCount=0]```

Nothing in UI as result

**Comment by kunal-deshmukh-deltatre** [comment]
Hello Maintainers and contributors, 
I had an official call with SonarSource they have said it is the issue with the plugin as part of enterprise support - Can you please help or shed some light so that we know what is the exact cause here?

**Comment by Reamer** [comment]
If it works with a local SonarQube server, but not with another SonarQube, the assumption is that it is at the other SonarQube server due to something persistent in the storage backend.
The plugin itself has no state and uses the SonarQube API to store values and issues in the SonarQube server.
The plugin itself is significantly written and maintained by me. Unfortunately I don't have the possibility to test this plugin on a commercial version.
Also I don't get any money to provide support. All activities are done in my spare time.

**Comment by kunal-deshmukh-deltatre** [comment]
I think some issue with Sonarsource enterprise edition which broke the working of this plugin. I will let you know if it works in future. Thanks.
