### ISSUE TITLE
CPE Confidence not showing anything

### ISSUE THREAD

**Issue by eliassal** [dependency-check/dependency-check-sonar-plugin#729]
**Describe the bug**
I started using this interesting tool today and I was able to configure to run from command line as well as from Azure Devops server build pipeline.
I understand from the topic "How to read the report " that "CPE Confidence - a ranking of how confident dependency-check is that the CPE was identified correctly" for some project I dont get anything in the column as you can notice in the snapshot

**Expected behavior**
See CPE Confidence as indicated in the help file
**Screenshots**
![image](https://user-images.githubusercontent.com/8447864/203832225-a850950f-4a07-41a2-8c57-e0a76c73e3a3.png)

**Versions (please complete the following information):**

-   dependency-check : 3.0.1 on both environments
-   sonarqube : 9.6 community  and 9.7 Enterprise
-   dependency-check-sonar-plugin  downloaded the zip version this morning, not sure how to get the version

**Additional context**

**Comment by aikebah** [comment]
@eliassal You filed this issue in the wrong project. This project is for the Sonar plugin that reads these reports. 

The github of dependency-check is hosted at https://github.com/jeremylong/DependencyCheck/

The confidence column indicates how confident the algorithm in the tool is that the data listed under 'vulnerability IDs' is correct. As none of your libraries was linked to a CPE (Vulnerability ID column is empty) there is also no data on the confidence of the correctness of the linkage.

**Comment by Reamer** [comment]
Thanks @aikebah

**Comment by eliassal** [comment]
Thanks
