### ISSUE TITLE
When accessing the "Dependency-Check" tab in SonarQube UI, a red box with text "Page extension failed" is shown

### ISSUE THREAD

**Issue by perostman** [dependency-check/dependency-check-sonar-plugin#804]
**Describe the bug**
After running a sonar scan via Jenkins, configured to upload the dependency-check report(s) as well, when accessing the "Dependency-Check" tab in SonarQube UI, I get a red box with the text "Page extension failed"

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install & setup SonarQube, install the dependency-check plugin, version 3.1.0
2. Run a jenkins job that compiles and runs a dependency-check scan followed by a sonar scan using maven. Sonar scan properties set to upload the dependency-check report(s)
3. Login to SonarQube, access the "Dependency-Check" tab
4. See error - a red box with text "Page extension failed"

**Current behavior**
When accessing the "Dependecny-Check" tab, a red box with text "Page extension failed" is shown

**Expected behavior**
Seeing the dependency-check report in the SonarQube UI

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check (maven): Tested with 8.1.0 & 8.2.1
-   sonarqube 10.0.0
-   dependency-check-sonar-plugin 3.10.0

**Additional context**
Excerpt from sonar-project.properties:
sonar.dependencyCheck.jsonReportPath=modules/target/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=modules/target/dependency-check-report.html
sonar.dependencyCheck.reportPath=modules/target/dependency-check-report.xml
sonar.dependencyCheck.securityHotspot=true
sonar.dependencyCheck.useFilePath=true

Excerpt from Jenkins console log for the Sonar scanner part:
21:43:49  INFO: ------------- Run sensors on project
21:43:49  INFO: Sensor Dependency-Check [dependencycheck]
21:43:49  INFO: Process Dependency-Check report
21:43:49  INFO: Using JSON-Reportparser
21:43:51  INFO: Linking 187 dependencies
21:43:51  INFO: Upload Dependency-Check HTML-Report
21:43:51  INFO: Process Dependency-Check report (done) | time=1675ms
21:43:51  INFO: Sensor Dependency-Check [dependencycheck] (done) | time=1676ms

Screenshot:
![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/14905019/44e507cf-d45a-4eb1-8af8-10a66b9a9d2a)

**Comment by Reamer** [comment]
Please update to the [4.0.0](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/tag/4.0.0)
See https://github.com/dependency-check/dependency-check-sonar-plugin/issues/779 for more information.
