### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by pjk6** [dependency-check/dependency-check-sonar-plugin#805]
Hi,

Inside the README file in the Plugin compatability table release 4.0.0 and up is mentioned. But version 4.0.0 is not availlable as a release. When do you expect to release version 4.0.0?

Kind regards,

Peter

**Comment by perostman** [comment]
It is released now.

**Comment by Reamer** [comment]
The update for the Marketplace has just been placed.
https://github.com/SonarSource/sonar-update-center-properties/pull/413
