### ISSUE TITLE
DependencyCheck reports uploaded to SonarQube has the "suppress" button disabled

### ISSUE THREAD

**Issue by perostman** [dependency-check/dependency-check-sonar-plugin#806]
**Describe the bug**
When uploading the dependency check report to, when accessing the report, the "suppress" button in the report is disabled

**To Reproduce**
1. Sonarqube 10.0.0 with Dependency-Check plugin 4.0.0
2. Produce a dependencycheck report and upload it to SonarQube
3. Access the dependency check report in SonarQube
4. Observe that the "Suppress" buttons are disabled

**Current behavior**
The "Suppress" buttons are disabled.

**Expected behavior**
The "Suppress" buttons are enabled.

**Screenshots**
**Error:**
![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/14905019/b026b58e-2b8a-48c3-b2ff-749f4a7d50a1)

**Expected:**
![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/14905019/d88ff56c-6c38-4b01-a4ad-9e3e89b3b352)

**Versions (please complete the following information):**
-   dependency-check 8.2.1
-   sonarqube 10.0.0
-   dependency-check-sonar-plugin 4.0.0

**Additional context**

**Comment by perostman** [comment]
@Reamer I am not sure how I would apply this patch - could you please point me to how to do this?

**Comment by Reamer** [comment]
- check out the plugin on your local computer
- Apply the patch
- Compile the plugin
- Add the plugin to your SonarQube

**Comment by perostman** [comment]
Tried (compiled using `mvn clean package -Dlicense.skip` since I got errors on license check).

Getting compilation error;

`[INFO] [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'sonar-helpers' in '/home/postman/github/depcheck/dependency-check-sonar-plugin/sonar-dependency-check-plugin/src/main/js/report_page/components'
`
Maybe something is missing from the instructions on how to setup for compilation?

**Comment by Reamer** [comment]
I think you have not applied the patch correctly. Do you have a GitHub repo where I can look over it?

**Comment by allej** [comment]
Hi,
same issue here...

I've built the plugin using current master and changes from #765.
Now, the dependency check report opens nicely in a new browser tab, but the "suppress" button still does not work.
The error message in the browser console is
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).  report_page.js:1:8126`

**Comment by perostman** [comment]
Are there any updates after comment from @allej ?
