### ISSUE TITLE
 Dependency-Check Page extension failed in community edition

### ISSUE THREAD

**Issue by parth42** [dependency-check/dependency-check-sonar-plugin#807]
**Describe the bug**
After installing Dependency-Check, trying to open it in SonarQube community edition but encountering an error, "extension failed"

**To Reproduce**
After installing and restarting the server, when tried to open a report it gives extension error. 

**Current behavior**
does not open

**Expected behavior**
should open report after installation

**Screenshots**
![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/6380576/3c4e9ce4-3bdc-4b66-a457-baa774511013)

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/6380576/fe9ac709-dfbd-4ada-bb7e-cd668a4fed25)

**Versions (please complete the following information):**

-   dependency-check: 8.2.1
-   sonarqube: 10
-   dependency-check-sonar-plugin: 3.1.0

**Comment by perostman** [comment]
Try using version 4.0.0 of the plugin, worked for me.

**Comment by Reamer** [comment]
Please update to the new plugin version.
The update for the Marketplace has just been placed.
https://github.com/SonarSource/sonar-update-center-properties/pull/413
