### ISSUE TITLE
Quality gate uses original severity of the issue, not the user assigned one

### ISSUE THREAD

**Issue by michalszelagsonos** [dependency-check/dependency-check-sonar-plugin#829]
**Describe the bug**
I have several vulnerabilities detected by the dependency-check which show up in the report.  They are marked with medium and high severity.  After review, I downgraded them to minor severity using the SQ UI.  In my quality gate, I set the rules to fail as follows in overall code:
- critical vulnerabilities > 0
- high vulnerabilities > 0
- medium vulnerabilities > 0

As a result, my scan should now pass since all issues in the report are set to minor severity.  A subsequent scan fails reporting the original severity of the issues: 4 high, 1 medium.  It appears that the severity I assigned to the issues is being ignored by the quality gate.

Note, the options in the quality gate coming from the plugin do not map exactly to the severity names in the issues, perhaps this is a source of the problem?  The options offered in the quality gate related to vulnerability severity:
- critical
- high
- medium
- low

The issues that are detected by the check have the following options in the UI:
- blocker
- critical
- major
- minor
- info

**To Reproduce**
- Run a dependency check and a scan that detects a vulnerability, and note the severity of it.
- In SonarQube, go to the report and downgrade the severity to Minor.
- In the quality gate, set the fail threshold such that all minor vulnerabilities are ignored (critical > 0, high > 0, medium > 0).
- Run the scan again, note that the scan fails reporting original severity of the issue, the user defined severity is ignored.

**Current behavior**
Quality gate seems to be using the original severity of the vulnerability rather than user defined one.

**Expected behavior**
Quality gate should be using the severity of a vulnerability that is set in SonarQube.

**Versions (please complete the following information):**

-   dependency-check 8.3.1
-   sonarqube 10.0
-   dependency-check-sonar-plugin 4.0.0

**Comment by michalszelagsonos** [comment]
This is still a valid issue, keep it open bot overseers.

**Comment by michalszelagsonos** [comment]
Please keep alive, still a valid issue.

**Comment by Reamer** [comment]
Because the plugin creates only two rules in SonarQube, the severity is always overwritten. Maybe this leads to the problem.

https://github.com/dependency-check/dependency-check-sonar-plugin/blob/05836f048c56616c2cebbcf569064915f3476ddb/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReason.java#L111C31-L111C39

https://github.com/dependency-check/dependency-check-sonar-plugin/blob/05836f048c56616c2cebbcf569064915f3476ddb/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/reason/DependencyReason.java#L132

Right now, I don't know how we're going to stop that.

**Comment by Reamer** [comment]
How does it behave with other issue and the quality gate? Maybe it is a SonarQube bug.

**Comment by michalszelagsonos** [comment]
SonarQube recently changed how severity is managed and changing severity directly is no longer supported.  From https://docs.sonarsource.com/sonarqube/10.2/user-guide/issues/:

```
Info: The old severity feature is deprecated. It is no longer possible to change the severity of an issue. Severity is now tied to the software qualities impacted. 
```

Given this context, I think this issue can be closed although I suspect the plugin needs to be updated to conform to use severity mapping and not use deprecated values.
