### ISSUE TITLE
Can't see CVEs (vulnerabilities) on Sonar UI under Project>Issues. Used to see them in the past. Has anything changed?

### ISSUE THREAD

**Issue by mansing2** [dependency-check/dependency-check-sonar-plugin#834]
**Describe the bug**
We're using a combination of Jenkins and Sonar Plugin of DependencyCheck. The reports in HTML and JSON getting generated during pipeline build in Jenkins and also could see html reports from Project>More>Dependency Check, but the vulnerabilities (CVEss) are no longer listed under Project>Issues>Security Category>OWASP Top 10. We were able to see the CVEs there in the past.

Has anything been changed?

**Expected behavior**
It should show CVEs identified under OWASP TOP 10 category under Issues like we used to see in the past as below.

**Screenshots**
![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/25703880/f8d6c02b-873b-4e34-b1fb-15bd19e23844)

**Versions (please complete the following information):**
Jenkins Dependency Check plugin: 5.4.0
Sonar Dependency check plugin: 3.0.1

I read about this https://sonarsource.atlassian.net/browse/SONAR-11970 but not sure if that's the reason behind now showing up CVEs under OWASP Top 10 category.

**Comment by Reamer** [comment]
Which version of SonarQube are you using? I have two categories and the issues are displayed in both. I am currently using the latest SonarQube LTS version.
![grafik](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/454320/7c8e8edf-93a6-4552-b4f9-fa5f658dca1e)

**Comment by aikebah** [comment]
@mansing2 Could it be that this was your first time using DependencyCheck 8.x for your analysis on Jenkins? (The Jenkins plugin is a wrapper that can run different version of DependencyCheck CLI) See #748

**Comment by gusriobr** [comment]
I'm having the same problem, after upgrading the maven dep-check plugin from 7.1.1 to 8.4.0, the vulnerabilities disappered from project issue section in sonarQube.

We run the report generation with this line:
```
mvn org.owasp:dependency-check-maven:8.4.0:check -Dformats=xml,html,json
```
After this, the reports can be found under target/ folder, but comparing the 8.4 and 7.1.1 version shows some diffs in the xml formats

This is our SonarQube version.
Community EditionVersion 8.9.10 (build 61524)

**Comment by aikebah** [comment]
@gusriobr That would then be something for an issue at https://github.com/dependency-check/dependency-check-sonar-plugin/issues

DependencyCheck's  responsibility stops at the creation of the report files. How the information in those reports is put into the SonarQube issue registration is decided upon in the SonarQube plugin project (and may potentially be constrained by internal changes within SonarQube)

**Comment by muratkucuktepe** [comment]
> 8.9.10

I have also the same problem.
Sonarqube: 8.9.1
Sonar Scanner Plugin: 4.3.1.3277
Gradle: 8.3
Dependency Checker 8.4.0. 

Problem is that Sonarqube can not parse the json report because of "includedBy" property.
