### ISSUE TITLE
Examples and tests still use removed `sonar.dependencyCheck.reportPath` property

### ISSUE THREAD

**Issue by maloewe-ona** [dependency-check/dependency-check-sonar-plugin#846]
**Describe the bug**
#755 removed the property `sonar.dependencyCheck.reportPath`.

However, there are still multiple references to this property:
- https://github.com/dependency-check/dependency-check-sonar-plugin/blob/cff3469ecd50f83422a0e4c323ef6f019a6bdf92/examples/single-module-maven/pom.xml#L21
- https://github.com/dependency-check/dependency-check-sonar-plugin/blob/cff3469ecd50f83422a0e4c323ef6f019a6bdf92/sonar-dependency-check-plugin/src/test/resources/reason/build.gradle#L38
- https://github.com/dependency-check/dependency-check-sonar-plugin/blob/cff3469ecd50f83422a0e4c323ef6f019a6bdf92/sonar-dependency-check-plugin/src/test/resources/reason/pom.xml#L28
- https://github.com/dependency-check/dependency-check-sonar-plugin/blob/cff3469ecd50f83422a0e4c323ef6f019a6bdf92/sonar-dependency-check-plugin/src/test/resources/reason/build.gradle.kts#L31

Is there maybe also something wrong with the test setup since the usage of that removed property is apparently not causing a test failure?

**Expected behavior**
There should not be any references to `sonar.dependencyCheck.reportPath` anymore; or they should at least say that only older versions of the plugin supported this property.

**Comment by Reamer** [comment]
Thank you, I closed the MR by mistake. With https://github.com/dependency-check/dependency-check-sonar-plugin/pull/926 the property should no longer occur.
