### ISSUE TITLE
Suggested Changes for SonarQube Marketplace

### ISSUE THREAD

**Issue by bradflood** [dependency-check/dependency-check-sonar-plugin#85]
Reference: https://community.sonarsource.com/t/new-plugin-dependencycheck-requesting-inclusion-in-sonarqube-marketplace/3743/3 

Suggested README changes
- [x] change single-module example to include install goal (eg: mvn install sonar:sonar instead of mvn sonar:sonar)
- [x] change multi-module example to include install goal, and use Maven Scanner (eg: mvn install sonar:sonar instead of sonar-runner)

Suggested Scanner changes
- [x] Create issues against the POM file, identifying the lines declaring the vulnerable dependency

The reviewer suggests a few capabilities that are already provided, so we may need to improve the documentation to make this more apparent. 

These all appear to be reasonable suggestions, and I suggest we incorporate them in the next build. I'll have time in a few weeks, but if someone else wants to take it, that would be great.

**Comment by Reamer** [comment]
We shouldn't use "mvn install" in our example, better is "**mvn package**"

WIP-Commit to create issues against the POM file https://github.com/Reamer/dependency-check-sonar-plugin/commit/c9a3abdf6ad46b7246db08a3a6bedbf7d89fc9e4

**Comment by bradflood** [comment]
agree - mvn package is better

@Reamer  nice work on the code to create issues against the POM.  If you wanted to submit a PR, I think we can tackle transitive dependencies in a separate pass.  Would be nice to have a test to accompany it

**Comment by Reamer** [comment]
Updated single-module-maven example in https://github.com/stevespringett/dependency-check-sonar-plugin/commit/bc5928b05beba239d5ef6a9ae1eaca4ea12e95fe

**Comment by Reamer** [comment]
Updated multi-module-maven example in https://github.com/stevespringett/dependency-check-sonar-plugin/commit/2ad42363becad492afa10087df7f5964df1bf08e

**Comment by Reamer** [comment]
Create issues against the POM file done in https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/commit/09e9fe8a72c5b908df5d9bb159f283b604b59852

**Comment by Reamer** [comment]
Thanks for the input.
- [ ] Check code via SonarCloud

**Comment by Reamer** [comment]
@jeremylong 
You should receive a request for sonarcloud.io to move forward in this issue.

**Comment by Reamer** [comment]
Hi @jeremylong 
Thanks for creating the organization [dependency-check in sonarcloud.io](https://sonarcloud.io/organizations/dependency-check/). I have problems to create a new project with "Set up manually". I get the error "Insufficient privileges". Can you increase my privileges?

**Comment by Reamer** [comment]
For the automated verification of the code quality, we use sonarcloud since today.

**Comment by Reamer** [comment]
PR for marketplace: https://github.com/SonarSource/sonar-update-center-properties/pull/85

**Comment by Reamer** [comment]
We are finally in the sonarqube marketplace 🎉
