### ISSUE TITLE
Cannot collspae Published Vulnerabilities in SonarQube

### ISSUE THREAD

**Issue by dennys** [dependency-check/dependency-check-sonar-plugin#858]
**Describe the bug**
I can generate report in SonarQube (from "More" -> "Dependency-Check" to see it)
But when I try to click collpae button on "Published Vulnerabilities", it doesn't work.
I'm not familiar with HTML (or javascript), it seems due to iframe?

**Expected behavior**
I should collapse "Published Vulnerabilities"

**Versions
-   dependency-check 8.4.0
-   sonarqube 10.2.1
-   dependency-check-sonar-plugin 4.0.0
-   Chrome 116.0.5845.180

**Comment by dennys** [comment]
Do I need to build it to test? I try to check /extensions/plugins/sonar-dependency-check-plugin-4.0.0.jar, but I don't find DependencyCheckReportApp.js
Is it possible to just replace the js to test? Because it seems need to prepare a Java venrionment to build this plugin.

**Comment by Reamer** [comment]
Yes you need to manually add these changes to the code, then build the plugin and deposit it in SonarQube extension folder.

**Comment by dennys** [comment]
Got it... but it's not easy for me to build the Java environment, is it possible to provide a jar, I can download it to manual test?

**Comment by dennys** [comment]
> Yes you need to manually add these changes to the code, then build the plugin and deposit it in SonarQube extension folder.

Hi, I try to build this plugin, I can build 4.0 now. But I'm not sure how to apply the PR to my code,
so, I try to download it from https://github.com/brileyd/dependency-check-sonar-plugin/tree/brileyd-patch-1
But it generates sonar-dependency-check-plugin-3.1.1-SNAPSHOT.jar, is it correct?
This PR is created before 4.0, it seems correct... what should I do? Test 3.1.1?
