### ISSUE TITLE
NVD Api key config missing

### ISSUE THREAD

**Issue by czechdude** [dependency-check/dependency-check-sonar-plugin#891]
We get this message when using the dependency check plugin in SonarQube when running as Azure Devops pipeline task:
`[WARN] An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key`

So we would like a way how to configure this NVD API Key in so it does not take VERY long time.

Running plugin 4.0.0.0, SQ 9.9.2

Thanks!

**Comment by Reamer** [comment]
This output does not come from this plugin. I think you should post your problem here. https://github.com/dependency-check/azuredevops
