### ISSUE TITLE
Issue with Documentation for 10.2+

### ISSUE THREAD

**Issue by kantipenko** [dependency-check/dependency-check-sonar-plugin#908]
I think documentation contains mistype, there is not 5.0.0 plugin release, latest one is 4.0.1 but documentation says that SQ 10.3 is supported by 5.0.0 plugin that is not existent.  Please see screenshot below:

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/44398196/6111b701-1ee2-4955-868f-fdd27c7e14d7)

**Comment by Reamer** [comment]
I have just released 5.0.0. Sorry for the delay. The documentation should now fit again and I am closing the issue.
