### ISSUE TITLE
Release 5.0 not compatible with SonarQube 9.9 LTA

### ISSUE THREAD

**Issue by alixwar** [dependency-check/dependency-check-sonar-plugin#953]
From the release notes:

> Drop JDK11 Support and add JDK21 Support (https://github.com/dependency-check/dependency-check-sonar-plugin/pull/903 by @Reamer)

SonarQube 9.9 LTA still supports analysis using JDK 11. Does this change mean this will not work (using a Sonar Scanner with JDK 11)?

**Comment by Reamer** [comment]
If you are using JDK11, you should use an older version.
