### ISSUE TITLE
high_severity_vulns\u0027 does not exist

### ISSUE THREAD

**Issue by Sam8301-arch** [dependency-check/dependency-check-sonar-plugin#971]
Hello team,

I am getting this error “Metric with key \u0027high_severity_vulns\u0027 does not exist (Visit of Component {key\u003dmicrosite:src/view,type\u003dDIRECTORY} failed)” on all sonarqube builds.

10.5.1. Version.
The error is coming for all the scans while using sonarqube

Do anyone know how to resolve this?

**Comment by Reamer** [comment]
I have no idea how this error occurs. Can you send me steps to reproduce it.

**Comment by Sam8301-arch** [comment]
i dont know how to reproduce it but its coming on every scan. is there anyway to remove this?

**Comment by Sam8301-arch** [comment]
I have reinstall that plugin and issue resolved.
